/// Returns a user-facing attachment title without the file extension.
String mediaTitleFromDisplayName(
  String displayName, {
  required String fallback,
}) {
  final name = _fileName(displayName.trim());
  if (name.isEmpty || _isAutogeneratedMediaName(name)) return fallback;

  final extension = _extensionOf(name);
  final title = extension.isEmpty
      ? name
      : name.substring(0, name.length - extension.length);
  return title.trim().isEmpty ? fallback : title.trim();
}

/// Builds a persisted display name while retaining the media file extension.
///
/// Attachment type detection relies on the extension, so a title such as
/// "Summer trip" remains stored as "Summer trip.mov".
String displayNameWithMediaTitle({
  required String title,
  required String currentDisplayName,
  String? localPath,
  String? url,
}) {
  var cleanTitle = title
      .trim()
      .replaceAll(RegExp(r'[\\/]'), '-')
      .replaceAll(RegExp(r'\s+'), ' ');
  if (cleanTitle.length > 120) cleanTitle = cleanTitle.substring(0, 120).trim();
  if (cleanTitle.isEmpty) return currentDisplayName;

  var extension = '';
  for (final candidate in [currentDisplayName, localPath, url]) {
    extension = _extensionOf(_fileName(candidate?.trim() ?? ''));
    if (extension.isNotEmpty) break;
  }

  if (extension.isNotEmpty &&
      cleanTitle.toLowerCase().endsWith(extension.toLowerCase())) {
    cleanTitle = cleanTitle.substring(0, cleanTitle.length - extension.length);
  }
  cleanTitle = cleanTitle.trim();
  return cleanTitle.isEmpty ? currentDisplayName : '$cleanTitle$extension';
}

String _fileName(String value) {
  if (value.isEmpty) return '';
  final path = Uri.tryParse(value)?.path ?? value;
  final name = path.split(RegExp(r'[\\/]')).last;
  try {
    return Uri.decodeComponent(name);
  } on FormatException {
    return name;
  }
}

String _extensionOf(String name) {
  final dot = name.lastIndexOf('.');
  if (dot <= 0 || dot == name.length - 1) return '';
  final extension = name.substring(dot);
  return RegExp(r'^\.[a-zA-Z0-9]{1,10}$').hasMatch(extension) ? extension : '';
}

bool _isAutogeneratedMediaName(String name) {
  final lower = name.toLowerCase();
  return lower.startsWith('image_picker_') ||
      lower.startsWith('file_picker_') ||
      lower.startsWith('edited image') ||
      lower == 'scan.jpg';
}
