import 'dart:async';
import 'dart:io';
import 'dart:ui' as ui;
import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:image_picker/image_picker.dart';
import 'package:ios_image_editor/ios_image_editor.dart';
import 'package:liquid_glass_widgets/liquid_glass_widgets.dart' as lg;
import 'package:quill_native_bridge/quill_native_bridge.dart';
import 'package:Note/core/theme/app_theme.dart';
import 'package:Note/core/theme/ios_semantic_colors.dart';
import 'package:Note/features/note/presentation/controllers/note_detail_controller.dart';
import 'package:Note/features/note/domain/entities/note_block.dart';
import 'package:Note/core/feedback/app_snackbar.dart';
import 'package:Note/core/utils/attachment_url.dart';
import 'package:Note/core/utils/image_pdf.dart';
import 'package:Note/core/utils/share_helper.dart';
import 'package:Note/features/note/presentation/widgets/note_video_attachment.dart';
import 'package:Note/features/note/presentation/widgets/note_scanned_pdf_attachment.dart';
import 'package:Note/features/note/presentation/widgets/note_media_context_menu.dart';
import 'package:Note/features/note/presentation/widgets/note_media_cursor_edges.dart';
import 'package:Note/features/note/presentation/widgets/note_media_title.dart';
import 'package:Note/features/note/presentation/widgets/image_overlay_composer_page.dart';
import 'package:Note/shared/widgets/glass_widgets.dart';

const _imageExtensions = {
  'jpg',
  'jpeg',
  'png',
  'gif',
  'heic',
  'heif',
  'webp',
  'bmp',
};

const _audioExtensions = {'m4a', 'mp3', 'wav', 'aac', 'caf', 'ogg'};

bool _isAutogeneratedName(String name) {
  final cleanName = name.trim();
  return cleanName.startsWith('image_picker_') ||
      cleanName.startsWith('file_picker_') ||
      cleanName.startsWith('Edited Image') ||
      cleanName == 'Scan.jpg';
}

bool _looksLikeImage(AttachmentBlock block) {
  for (final candidate in [block.displayName, block.localPath, block.url]) {
    final name = candidate?.trim() ?? '';
    if (name.isEmpty || !name.contains('.')) continue;
    if (_imageExtensions.contains(name.split('.').last.toLowerCase())) {
      return true;
    }
  }
  return false;
}

bool _looksLikeAudio(AttachmentBlock block) {
  for (final candidate in [block.displayName, block.localPath, block.url]) {
    final name = candidate?.trim() ?? '';
    if (name.isEmpty || !name.contains('.')) continue;
    if (_audioExtensions.contains(name.split('.').last.toLowerCase())) {
      return true;
    }
  }
  return false;
}

class NoteAttachmentBlock extends StatelessWidget {
  final AttachmentBlock block;
  final int blockIndex;
  final NoteDetailController controller;

  const NoteAttachmentBlock({
    super.key,
    required this.block,
    required this.blockIndex,
    required this.controller,
  });

  @override
  Widget build(BuildContext context) {
    if (looksLikeVideoAttachment(block)) {
      return Padding(
        padding: const EdgeInsets.only(top: 8, bottom: 16),
        child: NoteVideoAttachment(
          key: ValueKey('video-${block.id}'),
          block: block,
          blockIndex: blockIndex,
          controller: controller,
          isReadOnly: controller.isReadOnly.value,
          onDelete: () => controller.deleteBlock(blockIndex),
        ),
      );
    }

    if (_looksLikeAudio(block)) {
      return Padding(
        padding: const EdgeInsets.only(top: 8, bottom: 16),
        child: _AudioTile(
          key: ValueKey('audio-${block.id}'),
          block: block,
          blockIndex: blockIndex,
          isReadOnly: controller.isReadOnly.value,
          controller: controller,
          onDelete: () => controller.deleteBlock(blockIndex),
        ),
      );
    }

    if (!_looksLikeImage(block)) {
      final isPdf = looksLikePdf(block.displayName);
      if (isPdf) {
        return Padding(
          padding: const EdgeInsets.only(top: 8, bottom: 16),
          child: NotePdfAttachment(
            key: ValueKey('scanned-pdf-${block.id}'),
            block: block,
            blockIndex: blockIndex,
            controller: controller,
            isReadOnly: controller.isReadOnly.value,
            onDelete: () => controller.deleteBlock(blockIndex),
          ),
        );
      }
      return Padding(
        padding: const EdgeInsets.only(top: 8, bottom: 16),
        child: _FileTile(
          block: block,
          isReadOnly: controller.isReadOnly.value,
          isPdf: isPdf,
          onTap: () => _openOrShareFile(context),
          onDelete: () => controller.deleteBlock(blockIndex),
          onShare: () => _openOrShareFile(context),
          onCopy: () => unawaited(controller.copyAttachmentBlock(blockIndex)),
          onPaste: () => unawaited(
            controller.pasteClipboardContent(afterIndex: blockIndex),
          ),
          onCut: () => unawaited(controller.cutAttachmentBlock(blockIndex)),

          onEdit: isPdf
              ? () => controller.editPdfSourceImage(blockIndex)
              : null,
          onConvertToImage: isPdf
              ? () => controller.convertPdfToImage(blockIndex)
              : null,
        ),
      );
    }

    final theme = Theme.of(context);
    final isDark = theme.brightness == Brightness.dark;
    final name = block.displayName.trim();

    final semanticsLabel = (name.isEmpty || _isAutogeneratedName(name))
        ? 'note_editor_attachment_semantic_label'.tr
        : 'note_editor_attachment_named_semantic_label'.trParams({
            'name': name,
          });

    return Padding(
      padding: const EdgeInsets.only(top: 8, bottom: 16),

      child: LayoutBuilder(
        builder: (context, constraints) => _ImageTile(
          block: block,
          width: constraints.maxWidth,
          isReadOnly: controller.isReadOnly.value,
          semanticsLabel: semanticsLabel,
          isDark: isDark,
          onOpen: () => _openImagePreview(context),
          onAddImage: () => _addImageOverlay(context),
          onCopy: () => unawaited(_copyImage(context)),
          onPaste: () => unawaited(
            controller.pasteClipboardContent(afterIndex: blockIndex),
          ),
          onCut: () => unawaited(controller.cutAttachmentBlock(blockIndex)),
          onConvertToPdf: () => controller.convertAttachmentToPdf(blockIndex),
          onShare: () => _shareImage(context),
          onDelete: () => controller.deleteBlock(blockIndex),
          onTitleChanged: (title) =>
              controller.updateAttachmentTitle(blockIndex, title),
          onFocusBefore: () =>
              controller.focusTextBesideAttachment(blockIndex, after: false),
          onFocusAfter: () =>
              controller.focusTextBesideAttachment(blockIndex, after: true),
        ),
      ),
    );
  }

  Future<void> _openImageEditor(BuildContext context) async {
    if (controller.isReadOnly.value) return;

    String? pathToEdit = normalizeLocalPath(block.localPath);

    if (pathToEdit == null || !File(pathToEdit).existsSync()) {
      final networkUrl = normalizeAttachmentUrl(block.url);
      if (networkUrl != null && networkUrl.isNotEmpty) {
        await Get.showOverlay(
          asyncFunction: () async {
            pathToEdit = await controller.cacheAttachmentForEditing(networkUrl);
          },
          loadingWidget: const Center(
            child: CupertinoActivityIndicator(radius: 15, color: Colors.white),
          ),
        );
        if (pathToEdit == null) return;
      }
    }

    debugPrint('[IMAGE EDIT] Final Path: $pathToEdit');

    if (pathToEdit == null || !File(pathToEdit!).existsSync()) {
      AppSnackbar.error(
        'note_editor_error_title'.tr,
        'note_editor_image_source_unavailable'.tr,
      );
      return;
    }

    try {
      final String? editedPath = await IOSImageEditor.editImage(pathToEdit!);
      if (editedPath != null && editedPath.isNotEmpty) {
        controller.updateAttachmentImage(blockIndex, editedPath);
      }
    } catch (e) {
      debugPrint('Error opening native editor: $e');
      AppSnackbar.error(
        'note_editor_error_title'.tr,
        'note_editor_could_not_open_image_editor'.tr,
      );
    }
  }

  Future<void> _openImagePreview(BuildContext context) async {
    final path = await _resolveImagePath(context);
    if (path == null || !context.mounted) {
      AppSnackbar.info(
        'note_editor_not_available_title'.tr,
        'note_editor_image_not_on_device'.tr,
      );
      return;
    }

    await Navigator.of(context).push(
      CupertinoPageRoute<void>(
        fullscreenDialog: true,
        builder: (_) => _ImagePreviewPage(
          path: path,
          title: 'note_editor_image_fallback_name'.tr,
          onEdit: controller.isReadOnly.value
              ? null
              : () => _openImageEditor(context),
          onShare: () => _shareImage(context),
        ),
      ),
    );
  }

  Future<void> _addImageOverlay(BuildContext context) async {
    if (controller.isReadOnly.value) return;

    final basePath = await _resolveImagePath(context);
    if (basePath == null) {
      AppSnackbar.info(
        'note_editor_not_available_title'.tr,
        'note_editor_image_not_on_device'.tr,
      );
      return;
    }

    final pickedImage = await ImagePicker().pickImage(
      source: ImageSource.gallery,
    );
    if (pickedImage == null || !context.mounted) return;

    final composedPath = await Navigator.of(context).push<String>(
      CupertinoPageRoute(
        fullscreenDialog: true,
        builder: (_) => ImageOverlayComposerPage(
          baseImagePath: basePath,
          overlayImagePath: pickedImage.path,
        ),
      ),
    );
    if (composedPath == null || composedPath.isEmpty) return;

    try {
      final editedPath = await IOSImageEditor.editImage(composedPath);
      if (editedPath != null && editedPath.isNotEmpty) {
        controller.updateAttachmentImage(blockIndex, editedPath);
      }
    } catch (error) {
      debugPrint('[IMAGE OVERLAY EDIT ERROR] $error');
      AppSnackbar.error(
        'note_editor_error_title'.tr,
        'note_editor_could_not_open_image_editor'.tr,
      );
    }
  }

  Future<void> _shareImage(BuildContext context) async {
    final path = await _resolveImagePath(context);
    if (path == null) {
      AppSnackbar.info(
        'note_editor_not_available_title'.tr,
        'note_editor_image_not_on_device'.tr,
      );
      return;
    }
    if (!context.mounted) return;
    try {
      await shareXFilesSafely(context, [XFile(path)]);
    } catch (e) {
      debugPrint('[IMAGE SHARE ERROR] $e');
      AppSnackbar.error(
        'note_editor_error_title'.tr,
        'note_editor_could_not_share_image'.tr,
      );
    }
  }

  Future<void> _copyImage(BuildContext context) async {
    final path = await _resolveImagePath(context);
    if (path == null) {
      AppSnackbar.info(
        'note_editor_not_available_title'.tr,
        'note_editor_image_not_on_device'.tr,
      );
      return;
    }

    final stagedInApp = await controller.copyAttachmentBlock(
      blockIndex,
      showFeedback: false,
    );
    var copiedToDevice = false;
    try {
      final bridge = QuillNativeBridge();
      final supported = await bridge.isSupported(
        QuillNativeBridgeFeature.copyImageToClipboard,
      );
      if (supported) {
        await bridge.copyImageToClipboard(await File(path).readAsBytes());
        copiedToDevice = true;
      }
    } catch (error) {
      debugPrint('[SYSTEM IMAGE COPY ERROR] $error');
    }

    if (stagedInApp || copiedToDevice) {
      AppSnackbar.success('note_editor_image_copied'.tr);
    } else {
      AppSnackbar.error(
        'note_editor_error_title'.tr,
        'note_editor_could_not_copy_image'.tr,
      );
    }
  }

  Future<String?> _resolveImagePath(BuildContext context) async {
    final localPath = normalizeLocalPath(block.localPath);
    if (localPath != null && File(localPath).existsSync()) return localPath;

    final networkUrl = normalizeAttachmentUrl(block.url);
    if (networkUrl == null || networkUrl.isEmpty) return null;

    String? cachedPath;
    await Get.showOverlay(
      asyncFunction: () async {
        cachedPath = await controller.cacheAttachmentForEditing(networkUrl);
      },
      loadingWidget: const Center(
        child: CupertinoActivityIndicator(radius: 15, color: Colors.white),
      ),
    );
    if (!context.mounted || cachedPath == null) return null;
    return File(cachedPath!).existsSync() ? cachedPath : null;
  }

  Future<void> _openOrShareFile(BuildContext context) async {
    final path = normalizeLocalPath(block.localPath);
    if (path == null || !File(path).existsSync()) {
      AppSnackbar.info(
        'note_editor_not_available_title'.tr,
        'note_editor_file_not_on_device'.tr,
      );
      return;
    }
    try {
      await shareXFilesSafely(context, [XFile(path)]);
    } catch (e) {
      debugPrint('[FILE SHARE ERROR] $e');
      AppSnackbar.error(
        'note_editor_error_title'.tr,
        'note_editor_could_not_open_file'.tr,
      );
    }
  }
}

class _ImageTile extends StatefulWidget {
  final AttachmentBlock block;
  final double width;
  final bool isReadOnly;
  final bool isDark;
  final String semanticsLabel;
  final VoidCallback onOpen;
  final VoidCallback onAddImage;
  final VoidCallback onCopy;
  final VoidCallback onPaste;
  final VoidCallback onCut;
  final VoidCallback onConvertToPdf;
  final VoidCallback onShare;
  final VoidCallback onDelete;
  final ValueChanged<String> onTitleChanged;
  final VoidCallback onFocusBefore;
  final VoidCallback onFocusAfter;

  const _ImageTile({
    required this.block,
    required this.width,
    required this.isReadOnly,
    required this.isDark,
    required this.semanticsLabel,
    required this.onOpen,
    required this.onAddImage,
    required this.onCopy,
    required this.onPaste,
    required this.onCut,
    required this.onConvertToPdf,
    required this.onShare,
    required this.onDelete,
    required this.onTitleChanged,
    required this.onFocusBefore,
    required this.onFocusAfter,
  });

  @override
  State<_ImageTile> createState() => _ImageTileState();
}

enum _ImageViewSize { small, large }

class _ImageTileState extends State<_ImageTile> {
  _ImageViewSize _viewSize = _ImageViewSize.large;
  NoteMediaCursorSide? _cursorSide;

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        NoteMediaTitle(
          displayName: widget.block.displayName,
          fallbackTitle: 'note_editor_image_fallback_name'.tr,
          fixedTitle: 'note_editor_image_fallback_name'.tr,
          isReadOnly: widget.isReadOnly,
          onChanged: widget.onTitleChanged,
        ),
        Semantics(
          button: true,
          image: true,
          label: '${widget.semanticsLabel}${'note_editor_image_tap_hint'.tr}',
          child: GestureDetector(
            behavior: HitTestBehavior.opaque,
            onTap: _openImagePreview,
            onLongPress: _showContextMenu,
            child: _buildImage(),
          ),
        ),
      ],
    );
  }

  void _openImagePreview() {
    if (_cursorSide != null) setState(() => _cursorSide = null);
    widget.onOpen();
  }

  void _focusImageEdge(NoteMediaCursorSide side) {
    setState(() => _cursorSide = side);
    if (side == NoteMediaCursorSide.before) {
      widget.onFocusBefore();
    } else {
      widget.onFocusAfter();
    }
  }

  void _showContextMenu() {
    if (_cursorSide != null) setState(() => _cursorSide = null);
    Feedback.forLongPress(context);
    showGeneralDialog<void>(
      context: context,
      barrierDismissible: true,
      barrierLabel: MaterialLocalizations.of(context).modalBarrierDismissLabel,
      barrierColor: Colors.transparent,
      transitionDuration: const Duration(milliseconds: 220),
      pageBuilder: (dialogContext, _, _) => _ImageContextMenuOverlay(
        block: widget.block,
        viewSize: _viewSize,
        isReadOnly: widget.isReadOnly,
        onAddImage: widget.onAddImage,
        onCopy: widget.onCopy,
        onPaste: widget.onPaste,
        onCut: widget.onCut,
        onShare: widget.onShare,
        onChooseViewSize: _chooseViewSize,
        onConvertToPdf: widget.onConvertToPdf,
        onDelete: widget.onDelete,
      ),
      transitionBuilder: (_, animation, _, child) {
        final curved = CurvedAnimation(
          parent: animation,
          curve: Curves.easeOutCubic,
          reverseCurve: Curves.easeInCubic,
        );
        return FadeTransition(
          opacity: curved,
          child: ScaleTransition(
            scale: Tween<double>(begin: 0.97, end: 1).animate(curved),
            child: child,
          ),
        );
      },
    );
  }

  Future<void> _chooseViewSize() async {
    final selected = await showCupertinoModalPopup<_ImageViewSize>(
      context: context,
      builder: (sheetContext) => CupertinoActionSheet(
        title: Text('note_editor_view_as'.tr),
        actions: [
          CupertinoActionSheetAction(
            onPressed: () => Navigator.pop(sheetContext, _ImageViewSize.small),
            child: Text('note_editor_view_as_small'.tr),
          ),
          CupertinoActionSheetAction(
            onPressed: () => Navigator.pop(sheetContext, _ImageViewSize.large),
            child: Text('note_editor_view_as_large'.tr),
          ),
        ],
        cancelButton: CupertinoActionSheetAction(
          onPressed: () => Navigator.pop(sheetContext),
          child: Text(MaterialLocalizations.of(context).cancelButtonLabel),
        ),
      ),
    );
    if (!mounted || selected == null) return;
    setState(() => _viewSize = selected);
  }

  Widget _buildImage() {
    final block = widget.block;
    final isSmall = _viewSize == _ImageViewSize.small;
    final imageWidth = isSmall
        ? (widget.width * 0.55).clamp(140.0, 200.0)
        : widget.width;
    final hasFocusedEdge = _cursorSide != null;

    return Align(
      alignment: Alignment.centerLeft,
      child: Container(
        constraints: isSmall
            ? const BoxConstraints(minHeight: 120, maxHeight: 160)
            : const BoxConstraints(),
        width: imageWidth,
        decoration: BoxDecoration(
          border: Border.all(
            color: hasFocusedEdge
                ? AppTheme.folderYellow
                : widget.isDark
                ? Colors.white.withValues(alpha: 0.12)
                : Colors.black.withValues(alpha: 0.08),
            width: hasFocusedEdge ? 1.5 : 1,
          ),
          boxShadow: [
            BoxShadow(
              color: Colors.black.withValues(alpha: widget.isDark ? 0.2 : 0.06),
              blurRadius: 8,
              offset: const Offset(0, 3),
            ),
          ],
        ),
        child: SizedBox(
          width: double.infinity,
          height: isSmall ? 140 : null,
          child: Stack(
            fit: isSmall ? StackFit.expand : StackFit.loose,
            children: [
              ClipRect(
                child: _AttachmentImage(block: block, naturalSize: !isSmall),
              ),
              if (!widget.isReadOnly)
                Positioned.fill(
                  child: NoteMediaCursorEdges(
                    keyPrefix: 'image',
                    focusedSide: _cursorSide,
                    beforeSemanticLabel: 'note_editor_write_before_image'.tr,
                    afterSemanticLabel: 'note_editor_write_after_image'.tr,
                    onFocusBefore: () =>
                        _focusImageEdge(NoteMediaCursorSide.before),
                    onFocusAfter: () =>
                        _focusImageEdge(NoteMediaCursorSide.after),
                  ),
                ),
            ],
          ),
        ),
      ),
    );
  }
}

class _ImagePreviewPage extends StatelessWidget {
  final String path;
  final String title;
  final VoidCallback? onEdit;
  final VoidCallback onShare;

  const _ImagePreviewPage({
    required this.path,
    required this.title,
    required this.onEdit,
    required this.onShare,
  });

  void _edit(BuildContext context) {
    final edit = onEdit;
    if (edit == null) return;
    Navigator.of(context).pop();
    WidgetsBinding.instance.addPostFrameCallback((_) => edit());
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Scaffold(
      key: const ValueKey('image-preview-page'),
      backgroundColor: theme.scaffoldBackgroundColor,
      appBar: CustomGlassAppBar(
        key: const ValueKey('image-preview-app-bar'),
        toolbarHeight: 52,
        padding: const EdgeInsets.symmetric(horizontal: 16),
        backgroundColor: theme.scaffoldBackgroundColor,
        leading: CustomGlassButton(
          key: const ValueKey('image-preview-close'),
          semanticLabel: MaterialLocalizations.of(context).closeButtonTooltip,
          onPressed: () => Navigator.of(context).pop(),
          width: 44,
          height: 44,
          shape: GlassShape.circle,
          blur: 10,
          opacity: 0.15,
          thickness: 8,
          padding: EdgeInsets.zero,
          child: Icon(
            CupertinoIcons.xmark,
            color: theme.primaryColor,
            size: 22,
          ),
        ),
        title: Text(
          title,
          maxLines: 1,
          overflow: TextOverflow.ellipsis,
          style: theme.textTheme.titleMedium?.copyWith(
            fontWeight: FontWeight.w700,
            letterSpacing: -0.2,
          ),
        ),
        actions: [
          if (onEdit != null)
            CustomGlassButton(
              key: const ValueKey('image-preview-edit'),
              semanticLabel: 'note_editor_edit_image'.tr,
              onPressed: () => _edit(context),
              height: 44,
              borderRadius: 22,
              padding: const EdgeInsets.symmetric(horizontal: 16),
              blur: 10,
              opacity: 0.15,
              thickness: 8,
              child: Text(
                'folder_edit'.tr,
                style: TextStyle(
                  color: theme.colorScheme.onSurface,
                  fontSize: 17,
                ),
              ),
            ),
          CustomGlassButton(
            key: const ValueKey('image-preview-share'),
            semanticLabel: 'note_editor_share'.tr,
            onPressed: onShare,
            width: 44,
            height: 44,
            shape: GlassShape.circle,
            blur: 10,
            opacity: 0.15,
            thickness: 8,
            padding: EdgeInsets.zero,
            child: Icon(
              CupertinoIcons.share,
              color: theme.primaryColor,
              size: 22,
            ),
          ),
        ],
      ),
      body: SafeArea(
        top: false,
        child: Center(
          child: InteractiveViewer(
            key: const ValueKey('image-preview-content'),
            minScale: 0.8,
            maxScale: 5,
            child: Image.file(
              File(path),
              fit: BoxFit.contain,
              filterQuality: FilterQuality.high,
            ),
          ),
        ),
      ),
    );
  }
}

class _ImageContextMenuOverlay extends StatelessWidget {
  final AttachmentBlock block;
  final _ImageViewSize viewSize;
  final bool isReadOnly;
  final VoidCallback onAddImage;
  final VoidCallback onCopy;
  final VoidCallback onPaste;
  final VoidCallback onCut;
  final VoidCallback onShare;
  final VoidCallback onChooseViewSize;
  final VoidCallback onConvertToPdf;
  final VoidCallback onDelete;

  const _ImageContextMenuOverlay({
    required this.block,
    required this.viewSize,
    required this.isReadOnly,
    required this.onAddImage,
    required this.onCopy,
    required this.onPaste,
    required this.onCut,
    required this.onShare,
    required this.onChooseViewSize,
    required this.onConvertToPdf,
    required this.onDelete,
  });

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final screenSize = MediaQuery.sizeOf(context);
    final menuHeight = isReadOnly ? 174.0 : 458.0;
    final previewHeight = (screenSize.height - menuHeight - 110).clamp(
      180.0,
      520.0,
    );

    return Material(
      color: Colors.transparent,
      child: GestureDetector(
        behavior: HitTestBehavior.opaque,
        onTap: () => Navigator.pop(context),
        child: BackdropFilter(
          filter: ui.ImageFilter.blur(sigmaX: 12, sigmaY: 12),
          child: ColoredBox(
            color: theme.scaffoldBackgroundColor.withValues(alpha: 0.72),
            child: SafeArea(
              child: Center(
                child: SingleChildScrollView(
                  padding: const EdgeInsets.fromLTRB(24, 20, 24, 24),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      GestureDetector(
                        onTap: () {},
                        child: Container(
                          width: double.infinity,
                          height: previewHeight,
                          constraints: const BoxConstraints(maxWidth: 560),
                          decoration: BoxDecoration(
                            boxShadow: [
                              BoxShadow(
                                color: Colors.black.withValues(alpha: 0.22),
                                blurRadius: 28,
                                offset: const Offset(0, 14),
                              ),
                            ],
                          ),
                          child: ClipRect(
                            child: _AttachmentImage(block: block),
                          ),
                        ),
                      ),
                      const SizedBox(height: 24),
                      GestureDetector(
                        onTap: () {},
                        child: _ImageActionMenu(
                          viewSize: viewSize,
                          isReadOnly: isReadOnly,
                          onAddImage: () => _closeThen(context, onAddImage),
                          onCopy: () => _closeThen(context, onCopy),
                          onPaste: () => _closeThen(context, onPaste),
                          onCut: () => _closeThen(context, onCut),
                          onShare: () => _closeThen(context, onShare),
                          onChooseViewSize: () =>
                              _closeThen(context, onChooseViewSize),
                          onConvertToPdf: () =>
                              _closeThen(context, onConvertToPdf),
                          onDelete: () => _closeThen(context, onDelete),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }

  void _closeThen(BuildContext context, VoidCallback action) {
    Navigator.pop(context);
    WidgetsBinding.instance.addPostFrameCallback((_) => action());
  }
}

class _ImageActionMenu extends StatelessWidget {
  final _ImageViewSize viewSize;
  final bool isReadOnly;
  final VoidCallback onAddImage;
  final VoidCallback onCopy;
  final VoidCallback onPaste;
  final VoidCallback onCut;
  final VoidCallback onShare;
  final VoidCallback onChooseViewSize;
  final VoidCallback onConvertToPdf;
  final VoidCallback onDelete;

  const _ImageActionMenu({
    required this.viewSize,
    required this.isReadOnly,
    required this.onAddImage,
    required this.onCopy,
    required this.onPaste,
    required this.onCut,
    required this.onShare,
    required this.onChooseViewSize,
    required this.onConvertToPdf,
    required this.onDelete,
  });

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final divider = Divider(
      height: 1,
      indent: 54,
      color: theme.dividerColor.withValues(alpha: 0.32),
    );

    return ClipRRect(
      borderRadius: BorderRadius.circular(28),
      child: BackdropFilter(
        filter: ui.ImageFilter.blur(sigmaX: 24, sigmaY: 24),
        child: Container(
          width: 344,
          decoration: BoxDecoration(
            color: theme.colorScheme.surface.withValues(alpha: 0.88),
            borderRadius: BorderRadius.circular(28),
            border: Border.all(
              color: theme.colorScheme.onSurface.withValues(alpha: 0.08),
            ),
          ),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              _ImageActionRow(
                icon: CupertinoIcons.doc_on_doc,
                title: 'note_editor_copy'.tr,
                onTap: onCopy,
              ),
              if (!isReadOnly) ...[
                divider,
                _ImageActionRow(
                  icon: Icons.content_paste_rounded,
                  title: 'note_editor_paste'.tr,
                  onTap: onPaste,
                ),
                divider,
                _ImageActionRow(
                  icon: Icons.content_cut_rounded,
                  title: 'note_editor_cut'.tr,
                  onTap: onCut,
                ),
                divider,
                _ImageActionRow(
                  icon: CupertinoIcons.photo_on_rectangle,
                  title: 'note_editor_add_image'.tr,
                  onTap: onAddImage,
                ),
              ],
              divider,
              _ImageActionRow(
                icon: CupertinoIcons.share,
                title: 'note_editor_share'.tr,
                onTap: onShare,
              ),
              divider,
              _ImageActionRow(
                icon: CupertinoIcons.rectangle_grid_1x2,
                title: 'note_editor_view_as'.tr,
                subtitle: viewSize == _ImageViewSize.large
                    ? 'note_editor_view_as_large'.tr
                    : 'note_editor_view_as_small'.tr,
                trailing: const Icon(CupertinoIcons.chevron_forward, size: 17),
                onTap: onChooseViewSize,
              ),
              if (!isReadOnly) ...[
                divider,
                _ImageActionRow(
                  icon: CupertinoIcons.doc_richtext,
                  title: 'note_editor_convert_to_pdf'.tr,
                  onTap: onConvertToPdf,
                ),
                divider,
                _ImageActionRow(
                  icon: CupertinoIcons.trash,
                  title: 'note_editor_delete'.tr,
                  isDestructive: true,
                  onTap: onDelete,
                ),
              ],
            ],
          ),
        ),
      ),
    );
  }
}

class _ImageActionRow extends StatelessWidget {
  final IconData icon;
  final String title;
  final String? subtitle;
  final Widget? trailing;
  final bool isDestructive;
  final VoidCallback onTap;

  const _ImageActionRow({
    required this.icon,
    required this.title,
    required this.onTap,
    this.subtitle,
    this.trailing,
    this.isDestructive = false,
  });

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final color = isDestructive
        ? CupertinoColors.destructiveRed
        : theme.colorScheme.onSurface;

    return Semantics(
      button: true,
      child: InkWell(
        onTap: onTap,
        child: SizedBox(
          height: subtitle == null ? 56 : 68,
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 16),
            child: Row(
              children: [
                SizedBox(width: 28, child: Icon(icon, size: 23, color: color)),
                const SizedBox(width: 12),
                Expanded(
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        title,
                        style: theme.textTheme.titleMedium?.copyWith(
                          color: color,
                          fontSize: 17,
                          fontWeight: FontWeight.w500,
                        ),
                      ),
                      if (subtitle != null)
                        Text(
                          subtitle!,
                          style: theme.textTheme.bodySmall?.copyWith(
                            color: theme.colorScheme.onSurfaceVariant,
                            fontSize: 13,
                          ),
                        ),
                    ],
                  ),
                ),
                if (trailing != null)
                  IconTheme(
                    data: IconThemeData(color: color),
                    child: trailing!,
                  ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

class _AttachmentImage extends StatelessWidget {
  final AttachmentBlock block;
  final bool naturalSize;

  const _AttachmentImage({required this.block, this.naturalSize = false});

  Widget _placeholder() => naturalSize
      ? AspectRatio(aspectRatio: 4 / 3, child: _AttachmentPlaceholder())
      : _AttachmentPlaceholder();

  @override
  Widget build(BuildContext context) {
    final localPath = normalizeLocalPath(block.localPath);
    final networkUrl = normalizeAttachmentUrl(block.url);

    if (localPath != null) {
      final file = File(localPath);
      if (file.existsSync()) {
        return Image.file(
          file,
          key: ValueKey('local-${block.id}-$localPath'),
          width: double.infinity,
          height: naturalSize ? null : double.infinity,
          fit: naturalSize ? BoxFit.contain : BoxFit.cover,
          gaplessPlayback: true,
          frameBuilder: (_, child, frame, synchronouslyLoaded) =>
              naturalSize && frame == null && !synchronouslyLoaded
              ? _placeholder()
              : child,
          filterQuality: FilterQuality.medium,
          errorBuilder: (_, error, stackTrace) {
            return networkUrl == null
                ? _placeholder()
                : _NetworkAttachmentImage(
                    blockId: block.id,
                    url: networkUrl,
                    naturalSize: naturalSize,
                  );
          },
        );
      }
    }

    if (networkUrl != null) {
      return _NetworkAttachmentImage(
        blockId: block.id,
        url: networkUrl,
        naturalSize: naturalSize,
      );
    }

    return _placeholder();
  }
}

class _NetworkAttachmentImage extends StatelessWidget {
  final String blockId;
  final String url;
  final bool naturalSize;

  const _NetworkAttachmentImage({
    required this.blockId,
    required this.url,
    this.naturalSize = false,
  });

  Widget _placeholder() => naturalSize
      ? AspectRatio(aspectRatio: 4 / 3, child: _AttachmentPlaceholder())
      : _AttachmentPlaceholder();

  @override
  Widget build(BuildContext context) {
    return Image.network(
      url,
      key: ValueKey('network-$blockId-$url'),
      headers: attachmentAuthHeaders(),
      width: double.infinity,
      height: naturalSize ? null : double.infinity,
      fit: naturalSize ? BoxFit.contain : BoxFit.cover,
      gaplessPlayback: true,
      frameBuilder: (_, child, frame, synchronouslyLoaded) =>
          naturalSize && frame == null && !synchronouslyLoaded
          ? _placeholder()
          : child,
      filterQuality: FilterQuality.medium,
      loadingBuilder: (_, child, progress) {
        if (progress == null) return child;
        final totalBytes = progress.expectedTotalBytes;
        final value = totalBytes == null
            ? null
            : progress.cumulativeBytesLoaded / totalBytes;
        final indicator = Center(
          child: SizedBox(
            width: 24,
            height: 24,
            child: CircularProgressIndicator(
              value: value,
              color: Theme.of(context).primaryColor,
              strokeWidth: 2,
            ),
          ),
        );
        return naturalSize
            ? AspectRatio(aspectRatio: 4 / 3, child: indicator)
            : indicator;
      },
      errorBuilder: (_, _, _) => _placeholder(),
    );
  }
}

class _AttachmentPlaceholder extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return ColoredBox(
      color: theme.colorScheme.surface,
      child: Center(
        child: Icon(
          CupertinoIcons.photo,
          size: 27,
          color: theme.colorScheme.onSurfaceVariant,
        ),
      ),
    );
  }
}

class _FileTile extends StatefulWidget {
  final AttachmentBlock block;
  final bool isReadOnly;
  final bool isPdf;
  final VoidCallback onTap;
  final VoidCallback onDelete;
  final VoidCallback onShare;
  final VoidCallback onCopy;
  final VoidCallback onPaste;
  final VoidCallback onCut;

  final VoidCallback? onEdit;

  final VoidCallback? onConvertToImage;

  const _FileTile({
    required this.block,
    required this.isReadOnly,
    required this.onTap,
    required this.onDelete,
    required this.onShare,
    required this.onCopy,
    required this.onPaste,
    required this.onCut,
    this.isPdf = false,
    this.onEdit,
    this.onConvertToImage,
  });

  @override
  State<_FileTile> createState() => _FileTileState();
}

class _FileTileState extends State<_FileTile> {
  final _menuController = lg.GlassMenuController();

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final isDark = theme.brightness == Brightness.dark;
    final rawName = widget.block.displayName.trim();
    final name = (rawName.isEmpty || _isAutogeneratedName(rawName))
        ? 'note_editor_attachment_fallback_name'.tr
        : rawName;
    final ext = rawName.contains('.')
        ? rawName.split('.').last.toUpperCase()
        : '';

    return Semantics(
      button: true,
      label: 'note_editor_attached_file_semantic_label'.trParams({
        'name': name,
      }),
      child: lg.GlassMenu(
        controller: _menuController,
        menuWidth: 250,
        autoAdjustToScreen: true,
        menuPadding: const EdgeInsets.all(12),
        morphFromZero: true,
        triggerBuilder: (context, _) => GestureDetector(
          behavior: HitTestBehavior.opaque,
          onTap: widget.onTap,
          onLongPress: widget.isReadOnly ? null : _menuController.open,
          child: Container(
            padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(14),
              border: Border.all(
                color: isDark
                    ? Colors.white.withValues(alpha: 0.12)
                    : Colors.black.withValues(alpha: 0.08),
                width: 1,
              ),
            ),
            child: Row(
              children: [
                Container(
                  width: 40,
                  height: 40,
                  alignment: Alignment.center,
                  decoration: BoxDecoration(
                    color: theme.colorScheme.surfaceContainerHighest,
                    borderRadius: BorderRadius.circular(10),
                  ),
                  child: Icon(
                    widget.isPdf
                        ? CupertinoIcons.doc_richtext
                        : CupertinoIcons.doc,
                    size: 20,
                    color: theme.colorScheme.onSurfaceVariant,
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        name,
                        maxLines: 1,
                        overflow: TextOverflow.ellipsis,
                        style: theme.textTheme.bodyMedium?.copyWith(
                          fontWeight: FontWeight.w500,
                        ),
                      ),
                      if (ext.isNotEmpty)
                        Text(
                          ext,
                          style: theme.textTheme.bodySmall?.copyWith(
                            color: theme.colorScheme.onSurfaceVariant,
                          ),
                        ),
                    ],
                  ),
                ),
                if (!widget.isReadOnly) ...[
                  if (widget.onEdit != null) ...[
                    GestureDetector(
                      behavior: HitTestBehavior.opaque,
                      onTap: widget.onEdit,
                      child: Icon(
                        CupertinoIcons.pencil,
                        size: 18,
                        color: theme.colorScheme.onSurfaceVariant.withValues(
                          alpha: 0.6,
                        ),
                      ),
                    ),
                    const SizedBox(width: 12),
                  ],
                  GestureDetector(
                    behavior: HitTestBehavior.opaque,
                    onTap: widget.onShare,
                    child: Icon(
                      CupertinoIcons.square_arrow_up,
                      size: 18,
                      color: theme.colorScheme.onSurfaceVariant.withValues(
                        alpha: 0.6,
                      ),
                    ),
                  ),
                  const SizedBox(width: 12),
                  GestureDetector(
                    behavior: HitTestBehavior.opaque,
                    onTap: widget.onDelete,
                    child: Icon(
                      CupertinoIcons.trash,
                      size: 18,
                      color: theme.colorScheme.onSurfaceVariant.withValues(
                        alpha: 0.6,
                      ),
                    ),
                  ),
                ],
              ],
            ),
          ),
        ),
        items: [
          lg.GlassMenuItem(
            title: 'note_editor_copy'.tr,
            icon: const Icon(
              CupertinoIcons.doc_on_doc,
              color: IosSemanticColors.blue,
            ),
            onTap: widget.onCopy,
          ),
          lg.GlassMenuItem(
            title: 'note_editor_paste'.tr,
            icon: const Icon(
              Icons.content_paste_rounded,
              color: IosSemanticColors.blue,
            ),
            onTap: widget.onPaste,
          ),
          lg.GlassMenuItem(
            title: 'note_editor_cut'.tr,
            icon: const Icon(
              Icons.content_cut_rounded,
              color: IosSemanticColors.orange,
            ),
            onTap: widget.onCut,
          ),
          const lg.GlassMenuDivider(),
          if (widget.isPdf) ...[
            if (widget.onConvertToImage != null)
              lg.GlassMenuItem(
                title: 'note_editor_convert_to_image'.tr,
                icon: const Icon(
                  CupertinoIcons.photo,
                  color: IosSemanticColors.pink,
                ),
                onTap: widget.onConvertToImage!,
              ),
            if (widget.onEdit != null)
              lg.GlassMenuItem(
                title: 'note_editor_edit_original_image'.tr,
                icon: const Icon(
                  CupertinoIcons.pencil,
                  color: IosSemanticColors.blue,
                ),
                onTap: widget.onEdit!,
              ),
            const lg.GlassMenuDivider(),
          ],
          lg.GlassMenuItem(
            title: 'note_editor_open_share'.tr,
            icon: const Icon(
              CupertinoIcons.share,
              color: IosSemanticColors.blue,
            ),
            onTap: widget.onShare,
          ),
          if (!widget.isReadOnly) ...[
            const lg.GlassMenuDivider(),
            lg.GlassMenuItem(
              title: 'note_editor_delete'.tr,
              icon: const Icon(
                CupertinoIcons.trash,
                color: IosSemanticColors.red,
              ),
              isDestructive: true,
              onTap: widget.onDelete,
            ),
          ],
        ],
      ),
    );
  }
}

class _AudioTile extends StatefulWidget {
  final AttachmentBlock block;
  final int blockIndex;
  final bool isReadOnly;
  final NoteDetailController controller;
  final VoidCallback onDelete;

  const _AudioTile({
    super.key,
    required this.block,
    required this.blockIndex,
    required this.isReadOnly,
    required this.controller,
    required this.onDelete,
  });

  @override
  State<_AudioTile> createState() => _AudioTileState();
}

class _AudioTileState extends State<_AudioTile> {
  final _player = AudioPlayer();
  StreamSubscription<Duration>? _durationSub;
  StreamSubscription<Duration>? _positionSub;
  StreamSubscription<void>? _completeSub;

  Duration _duration = Duration.zero;
  Duration _position = Duration.zero;
  bool _isPlaying = false;

  bool _isLoading = false;
  String? _resolvedLocalPath;

  @override
  void initState() {
    super.initState();
    _durationSub = _player.onDurationChanged.listen((d) {
      if (mounted) setState(() => _duration = d);
    });
    _positionSub = _player.onPositionChanged.listen((p) {
      if (mounted) setState(() => _position = p);
    });
    _completeSub = _player.onPlayerComplete.listen((_) {
      if (mounted) {
        setState(() {
          _isPlaying = false;
          _position = Duration.zero;
        });
      }
    });

    final localPath = normalizeLocalPath(widget.block.localPath);
    if (localPath != null && File(localPath).existsSync()) {
      _resolvedLocalPath = localPath;
      unawaited(_player.setSourceDeviceFile(localPath));
    }
  }

  @override
  void dispose() {
    _durationSub?.cancel();
    _positionSub?.cancel();
    _completeSub?.cancel();
    _player.dispose();
    super.dispose();
  }

  Future<void> _togglePlay() async {
    if (_isPlaying) {
      await _player.pause();
      if (mounted) setState(() => _isPlaying = false);
      return;
    }

    final path = await _resolveLocalAudio();
    if (path == null) return;

    try {
      await _player.resume();
      if (mounted) setState(() => _isPlaying = true);
    } catch (e) {
      debugPrint('[AUDIO PLAY ERROR] $e');
      AppSnackbar.error(
        'note_editor_error_title'.tr,
        'note_editor_could_not_play_recording'.tr,
      );
    }
  }

  Future<String?> _resolveLocalAudio() async {
    final existingPath = _resolvedLocalPath;
    if (existingPath != null && File(existingPath).existsSync()) {
      return existingPath;
    }

    final networkUrl = normalizeAttachmentUrl(widget.block.url);
    if (networkUrl == null) {
      AppSnackbar.info(
        'note_editor_not_available_title'.tr,
        'note_editor_recording_not_on_device'.tr,
      );
      return null;
    }

    if (mounted) setState(() => _isLoading = true);
    final name = widget.block.displayName;
    final ext = name.contains('.') ? '.${name.split('.').last}' : '.m4a';
    final path = await widget.controller.cacheAttachmentForPlayback(
      networkUrl,
      extension: ext,
    );
    if (mounted) setState(() => _isLoading = false);
    if (path == null) return null;
    _resolvedLocalPath = path;
    await _player.setSourceDeviceFile(path);
    return path;
  }

  Future<void> _shareAudio() async {
    final path = await _resolveLocalAudio();
    if (path == null || !mounted) return;
    try {
      await shareXFilesSafely(context, [XFile(path)]);
    } catch (error) {
      debugPrint('[AUDIO SHARE ERROR] $error');
      AppSnackbar.error(
        'note_editor_error_title'.tr,
        'note_editor_could_not_share_recording'.tr,
      );
    }
  }

  void _showContextMenu(String name) {
    final theme = Theme.of(context);
    NoteMediaContextMenu.show(
      context: context,
      preview: _buildAudioPreview(theme, name),
      previewHeight: 180,
      actions: [
        NoteMediaMenuAction(
          title: 'note_editor_copy'.tr,
          icon: CupertinoIcons.doc_on_doc,
          onTap: () => unawaited(
            widget.controller.copyAttachmentBlock(widget.blockIndex),
          ),
        ),
        if (!widget.isReadOnly)
          NoteMediaMenuAction(
            title: 'note_editor_paste'.tr,
            icon: Icons.content_paste_rounded,
            onTap: () => unawaited(
              widget.controller.pasteClipboardContent(
                afterIndex: widget.blockIndex,
              ),
            ),
          ),
        if (!widget.isReadOnly)
          NoteMediaMenuAction(
            title: 'note_editor_cut'.tr,
            icon: Icons.content_cut_rounded,
            onTap: () => unawaited(
              widget.controller.cutAttachmentBlock(widget.blockIndex),
            ),
          ),
        if (!widget.isReadOnly)
          NoteMediaMenuAction(
            title: 'note_editor_delete'.tr,
            icon: CupertinoIcons.trash,
            isDestructive: true,
            onTap: widget.onDelete,
          ),
        NoteMediaMenuAction(
          title: 'note_editor_share'.tr,
          icon: CupertinoIcons.share,
          onTap: () => unawaited(_shareAudio()),
        ),
        NoteMediaMenuAction(
          title: 'note_editor_tap_to_play'.tr,
          icon: CupertinoIcons.play_fill,
          onTap: () => unawaited(_togglePlay()),
        ),
      ],
    );
  }

  Widget _buildAudioPreview(ThemeData theme, String name) {
    return ColoredBox(
      color: theme.colorScheme.surface,
      child: Padding(
        padding: const EdgeInsets.all(24),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Container(
              width: 64,
              height: 64,
              decoration: const BoxDecoration(
                color: AppTheme.folderPink,
                shape: BoxShape.circle,
              ),
              child: const Icon(
                CupertinoIcons.waveform,
                size: 30,
                color: Colors.white,
              ),
            ),
            const SizedBox(height: 14),
            Text(
              name,
              maxLines: 1,
              overflow: TextOverflow.ellipsis,
              style: theme.textTheme.titleMedium?.copyWith(
                fontWeight: FontWeight.w600,
              ),
            ),
            const SizedBox(height: 4),
            Text(
              _duration > Duration.zero
                  ? _format(_duration)
                  : 'note_editor_tap_to_play'.tr,
              style: theme.textTheme.bodySmall?.copyWith(
                color: theme.colorScheme.onSurfaceVariant,
              ),
            ),
          ],
        ),
      ),
    );
  }

  String _format(Duration d) {
    final minutes = d.inMinutes.remainder(60).toString().padLeft(2, '0');
    final seconds = d.inSeconds.remainder(60).toString().padLeft(2, '0');
    return '$minutes:$seconds';
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final isDark = theme.brightness == Brightness.dark;
    final rawName = widget.block.displayName.trim();
    final name = (rawName.isEmpty || _isAutogeneratedName(rawName))
        ? 'note_editor_recording_fallback_name'.tr
        : rawName;
    final hasDuration = _duration > Duration.zero;

    return Semantics(
      button: true,
      label: 'note_editor_audio_recording_semantic_label'.trParams({
        'name': name,
      }),
      child: GestureDetector(
        behavior: HitTestBehavior.opaque,
        onLongPress: () => _showContextMenu(name),
        child: Container(
          padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(14),
            border: Border.all(
              color: isDark
                  ? Colors.white.withValues(alpha: 0.12)
                  : Colors.black.withValues(alpha: 0.08),
              width: 1,
            ),
          ),
          child: Row(
            children: [
              GestureDetector(
                behavior: HitTestBehavior.opaque,
                onTap: _isLoading ? null : _togglePlay,
                child: Container(
                  width: 40,
                  height: 40,
                  alignment: Alignment.center,
                  decoration: const BoxDecoration(
                    color: AppTheme.folderPink,
                    shape: BoxShape.circle,
                  ),
                  child: _isLoading
                      ? const SizedBox(
                          width: 16,
                          height: 16,
                          child: CircularProgressIndicator(
                            strokeWidth: 2,
                            color: Colors.white,
                          ),
                        )
                      : Icon(
                          _isPlaying
                              ? CupertinoIcons.pause_fill
                              : CupertinoIcons.play_fill,
                          size: 18,
                          color: Colors.white,
                        ),
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Text(
                      name,
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                      style: theme.textTheme.bodyMedium?.copyWith(
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                    if (hasDuration)
                      SliderTheme(
                        data: SliderTheme.of(context).copyWith(
                          trackHeight: 2,
                          thumbShape: const RoundSliderThumbShape(
                            enabledThumbRadius: 5,
                          ),
                          overlayShape: const RoundSliderOverlayShape(
                            overlayRadius: 10,
                          ),
                        ),
                        child: Slider(
                          value: _position.inMilliseconds
                              .clamp(0, _duration.inMilliseconds)
                              .toDouble(),
                          max: _duration.inMilliseconds.toDouble(),
                          onChanged: (value) {
                            setState(
                              () => _position = Duration(
                                milliseconds: value.round(),
                              ),
                            );
                          },
                          onChangeEnd: (value) => _player.seek(
                            Duration(milliseconds: value.round()),
                          ),
                        ),
                      ),
                    Text(
                      hasDuration
                          ? '${_format(_position)} / ${_format(_duration)}'
                          : 'note_editor_tap_to_play'.tr,
                      style: theme.textTheme.bodySmall?.copyWith(
                        color: theme.colorScheme.onSurfaceVariant,
                      ),
                    ),
                  ],
                ),
              ),
              if (!widget.isReadOnly) ...[
                const SizedBox(width: 8),
                GestureDetector(
                  behavior: HitTestBehavior.opaque,
                  onTap: widget.onDelete,
                  child: Icon(
                    CupertinoIcons.trash,
                    size: 18,
                    color: theme.colorScheme.onSurfaceVariant.withValues(
                      alpha: 0.6,
                    ),
                  ),
                ),
              ],
            ],
          ),
        ),
      ),
    );
  }
}
