import 'dart:async';
import 'dart:io';
import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:ios_image_editor/ios_image_editor.dart';
import 'package:liquid_glass_widgets/liquid_glass_widgets.dart' as lg;
import 'package:share_plus/share_plus.dart';
import 'package:Note/core/theme/app_theme.dart';
import 'package:Note/core/theme/ios_semantic_colors.dart';
import 'package:Note/features/note/presentation/controllers/note_detail_controller.dart';
import 'package:Note/features/note/domain/entities/note_block.dart';
import 'package:Note/core/feedback/app_snackbar.dart';
import 'package:Note/core/utils/attachment_url.dart';
import 'package:Note/core/utils/image_pdf.dart';
import 'package:Note/core/utils/share_helper.dart';
import 'package:Note/features/note/presentation/widgets/note_video_attachment.dart';
import 'package:Note/features/note/presentation/widgets/note_scanned_pdf_attachment.dart';

const _imageExtensions = {
  'jpg',
  'jpeg',
  'png',
  'gif',
  'heic',
  'heif',
  'webp',
  'bmp',
};

const _audioExtensions = {'m4a', 'mp3', 'wav', 'aac', 'caf', 'ogg'};

bool _isAutogeneratedName(String name) {
  final cleanName = name.trim();
  return cleanName.startsWith('image_picker_') ||
      cleanName.startsWith('file_picker_') ||
      cleanName.startsWith('Edited Image') ||
      cleanName == 'Scan.jpg';
}

bool _looksLikeImage(AttachmentBlock block) {
  for (final candidate in [block.displayName, block.localPath, block.url]) {
    final name = candidate?.trim() ?? '';
    if (name.isEmpty || !name.contains('.')) continue;
    if (_imageExtensions.contains(name.split('.').last.toLowerCase())) {
      return true;
    }
  }
  return false;
}

bool _looksLikeAudio(AttachmentBlock block) {
  for (final candidate in [block.displayName, block.localPath, block.url]) {
    final name = candidate?.trim() ?? '';
    if (name.isEmpty || !name.contains('.')) continue;
    if (_audioExtensions.contains(name.split('.').last.toLowerCase())) {
      return true;
    }
  }
  return false;
}

class NoteAttachmentBlock extends StatelessWidget {
  final AttachmentBlock block;
  final int blockIndex;
  final NoteDetailController controller;

  const NoteAttachmentBlock({
    super.key,
    required this.block,
    required this.blockIndex,
    required this.controller,
  });

  @override
  Widget build(BuildContext context) {
    if (looksLikeVideoAttachment(block)) {
      return Padding(
        padding: const EdgeInsets.only(top: 8, bottom: 16),
        child: NoteVideoAttachment(
          key: ValueKey('video-${block.id}'),
          block: block,
          isReadOnly: controller.isReadOnly.value,
          onDelete: () => controller.deleteBlock(blockIndex),
        ),
      );
    }

    if (_looksLikeAudio(block)) {
      return Padding(
        padding: const EdgeInsets.only(top: 8, bottom: 16),
        child: _AudioTile(
          key: ValueKey('audio-${block.id}'),
          block: block,
          isReadOnly: controller.isReadOnly.value,
          controller: controller,
          onDelete: () => controller.deleteBlock(blockIndex),
        ),
      );
    }

    if (!_looksLikeImage(block)) {
      final isPdf = looksLikePdf(block.displayName);
      if (isPdf) {
        return Padding(
          padding: const EdgeInsets.only(top: 8, bottom: 16),
          child: NotePdfAttachment(
            key: ValueKey('scanned-pdf-${block.id}'),
            block: block,
            controller: controller,
            isReadOnly: controller.isReadOnly.value,
            onDelete: () => controller.deleteBlock(blockIndex),
          ),
        );
      }
      return Padding(
        padding: const EdgeInsets.only(top: 8, bottom: 16),
        child: _FileTile(
          block: block,
          isReadOnly: controller.isReadOnly.value,
          isPdf: isPdf,
          onTap: () => _openOrShareFile(context),
          onDelete: () => controller.deleteBlock(blockIndex),
          onShare: () => _openOrShareFile(context),

          onEdit: isPdf
              ? () => controller.editPdfSourceImage(blockIndex)
              : null,
          onConvertToImage: isPdf
              ? () => controller.convertPdfToImage(blockIndex)
              : null,
        ),
      );
    }

    final theme = Theme.of(context);
    final isDark = theme.brightness == Brightness.dark;
    final name = block.displayName.trim();

    final semanticsLabel = (name.isEmpty || _isAutogeneratedName(name))
        ? 'note_editor_attachment_semantic_label'.tr
        : 'note_editor_attachment_named_semantic_label'.trParams({
            'name': name,
          });

    return Padding(
      padding: const EdgeInsets.only(top: 8, bottom: 16),

      child: LayoutBuilder(
        builder: (context, constraints) => _ImageTile(
          block: block,
          width: constraints.maxWidth,
          isReadOnly: controller.isReadOnly.value,
          semanticsLabel: semanticsLabel,
          isDark: isDark,
          onEdit: () => _openImageEditor(context),
          onConvertToPdf: () => controller.convertAttachmentToPdf(blockIndex),
          onShare: () => _shareImage(context),
          onDelete: () => controller.deleteBlock(blockIndex),
        ),
      ),
    );
  }

  Future<void> _openImageEditor(BuildContext context) async {
    if (controller.isReadOnly.value) return;

    String? pathToEdit = normalizeLocalPath(block.localPath);

    if (pathToEdit == null || !File(pathToEdit).existsSync()) {
      final networkUrl = normalizeAttachmentUrl(block.url);
      if (networkUrl != null && networkUrl.isNotEmpty) {
        await Get.showOverlay(
          asyncFunction: () async {
            pathToEdit = await controller.cacheAttachmentForEditing(networkUrl);
          },
          loadingWidget: const Center(
            child: CupertinoActivityIndicator(radius: 15, color: Colors.white),
          ),
        );
        if (pathToEdit == null) return;
      }
    }

    debugPrint('[IMAGE EDIT] Final Path: $pathToEdit');

    if (pathToEdit == null || !File(pathToEdit!).existsSync()) {
      AppSnackbar.error(
        'note_editor_error_title'.tr,
        'note_editor_image_source_unavailable'.tr,
      );
      return;
    }

    try {
      final String? editedPath = await IOSImageEditor.editImage(pathToEdit!);
      if (editedPath != null && editedPath.isNotEmpty) {
        controller.updateAttachmentImage(blockIndex, editedPath);
      }
    } catch (e) {
      debugPrint('Error opening native editor: $e');
      AppSnackbar.error(
        'note_editor_error_title'.tr,
        'note_editor_could_not_open_image_editor'.tr,
      );
    }
  }

  Future<void> _shareImage(BuildContext context) async {
    final path = normalizeLocalPath(block.localPath);
    if (path == null || !File(path).existsSync()) {
      AppSnackbar.info(
        'note_editor_not_available_title'.tr,
        'note_editor_image_not_on_device'.tr,
      );
      return;
    }
    try {
      await shareXFilesSafely(context, [XFile(path)]);
    } catch (e) {
      debugPrint('[IMAGE SHARE ERROR] $e');
      AppSnackbar.error(
        'note_editor_error_title'.tr,
        'note_editor_could_not_share_image'.tr,
      );
    }
  }

  Future<void> _openOrShareFile(BuildContext context) async {
    final path = normalizeLocalPath(block.localPath);
    if (path == null || !File(path).existsSync()) {
      AppSnackbar.info(
        'note_editor_not_available_title'.tr,
        'note_editor_file_not_on_device'.tr,
      );
      return;
    }
    try {
      await shareXFilesSafely(context, [XFile(path)]);
    } catch (e) {
      debugPrint('[FILE SHARE ERROR] $e');
      AppSnackbar.error(
        'note_editor_error_title'.tr,
        'note_editor_could_not_open_file'.tr,
      );
    }
  }
}

class _ImageTile extends StatefulWidget {
  final AttachmentBlock block;
  final double width;
  final bool isReadOnly;
  final bool isDark;
  final String semanticsLabel;
  final VoidCallback onEdit;
  final VoidCallback onConvertToPdf;
  final VoidCallback onShare;
  final VoidCallback onDelete;

  const _ImageTile({
    required this.block,
    required this.width,
    required this.isReadOnly,
    required this.isDark,
    required this.semanticsLabel,
    required this.onEdit,
    required this.onConvertToPdf,
    required this.onShare,
    required this.onDelete,
  });

  @override
  State<_ImageTile> createState() => _ImageTileState();
}

class _ImageTileState extends State<_ImageTile> {
  final _menuController = lg.GlassMenuController();

  @override
  Widget build(BuildContext context) {
    return Semantics(
      button: true,
      image: true,
      label: '${widget.semanticsLabel}${'note_editor_image_tap_hint'.tr}',
      child: Stack(
        children: [
          lg.GlassMenu(
            controller: _menuController,
            menuWidth: 250,

            autoAdjustToScreen: true,
            menuPadding: const EdgeInsets.all(12),

            morphFromZero: true,
            triggerBuilder: (context, _) => GestureDetector(
              behavior: HitTestBehavior.opaque,

              onTap: widget.onEdit,
              onLongPress: _menuController.open,
              child: _buildImage(),
            ),
            items: _menuItems(),
          ),
        ],
      ),
    );
  }

  List<Widget> _menuItems() {
    return [
      lg.GlassMenuItem(
        title: 'note_editor_edit_image'.tr,
        icon: const Icon(CupertinoIcons.pencil, color: IosSemanticColors.blue),
        onTap: widget.onEdit,
      ),
      if (!widget.isReadOnly)
        lg.GlassMenuItem(
          title: 'note_editor_convert_to_pdf'.tr,
          icon: const Icon(
            CupertinoIcons.doc_richtext,
            color: IosSemanticColors.red,
          ),
          onTap: widget.onConvertToPdf,
        ),
      lg.GlassMenuItem(
        title: 'note_editor_share'.tr,
        icon: const Icon(CupertinoIcons.share, color: IosSemanticColors.blue),
        onTap: widget.onShare,
      ),
      if (!widget.isReadOnly) ...[
        const lg.GlassMenuDivider(),
        lg.GlassMenuItem(
          title: 'note_editor_delete'.tr,
          icon: const Icon(CupertinoIcons.trash, color: IosSemanticColors.red),
          isDestructive: true,
          onTap: widget.onDelete,
        ),
      ],
    ];
  }

  Widget _buildImage() {
    final block = widget.block;

    return Container(
      constraints: const BoxConstraints(maxHeight: 300, minHeight: 120),
      width: widget.width,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.zero,
        border: Border.all(
          color: widget.isDark
              ? Colors.white.withValues(alpha: 0.12)
              : Colors.black.withValues(alpha: 0.08),
          width: 1,
        ),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: widget.isDark ? 0.2 : 0.06),
            blurRadius: 8,
            offset: const Offset(0, 3),
          ),
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Stack(
          fit: StackFit.passthrough,
          children: [
            SizedBox(
              width: double.infinity,
              height: 240,
              child: _AttachmentImage(block: block),
            ),
          ],
        ),
      ),
    );
  }
}

class _AttachmentImage extends StatelessWidget {
  final AttachmentBlock block;

  const _AttachmentImage({required this.block});

  @override
  Widget build(BuildContext context) {
    final localPath = normalizeLocalPath(block.localPath);
    final networkUrl = normalizeAttachmentUrl(block.url);

    if (localPath != null) {
      final file = File(localPath);
      if (file.existsSync()) {
        return Image.file(
          file,
          key: ValueKey('local-${block.id}-$localPath'),
          width: double.infinity,
          height: double.infinity,
          fit: BoxFit.cover,
          gaplessPlayback: true,
          filterQuality: FilterQuality.medium,
          errorBuilder: (_, error, stackTrace) {
            return networkUrl == null
                ? _AttachmentPlaceholder()
                : _NetworkAttachmentImage(blockId: block.id, url: networkUrl);
          },
        );
      }
    }

    if (networkUrl != null) {
      return _NetworkAttachmentImage(blockId: block.id, url: networkUrl);
    }

    return _AttachmentPlaceholder();
  }
}

class _NetworkAttachmentImage extends StatelessWidget {
  final String blockId;
  final String url;

  const _NetworkAttachmentImage({required this.blockId, required this.url});

  @override
  Widget build(BuildContext context) {
    return Image.network(
      url,
      key: ValueKey('network-$blockId-$url'),
      headers: attachmentAuthHeaders(),
      width: double.infinity,
      height: double.infinity,
      fit: BoxFit.cover,
      gaplessPlayback: true,
      filterQuality: FilterQuality.medium,
      loadingBuilder: (_, child, progress) {
        if (progress == null) return child;
        final totalBytes = progress.expectedTotalBytes;
        final value = totalBytes == null
            ? null
            : progress.cumulativeBytesLoaded / totalBytes;
        return Center(
          child: SizedBox(
            width: 24,
            height: 24,
            child: CircularProgressIndicator(
              value: value,
              color: Theme.of(context).primaryColor,
              strokeWidth: 2,
            ),
          ),
        );
      },
      errorBuilder: (_, _, _) => _AttachmentPlaceholder(),
    );
  }
}

class _AttachmentPlaceholder extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return ColoredBox(
      color: theme.colorScheme.surface,
      child: Center(
        child: Icon(
          CupertinoIcons.photo,
          size: 27,
          color: theme.colorScheme.onSurfaceVariant,
        ),
      ),
    );
  }
}

class _FileTile extends StatefulWidget {
  final AttachmentBlock block;
  final bool isReadOnly;
  final bool isPdf;
  final VoidCallback onTap;
  final VoidCallback onDelete;
  final VoidCallback onShare;

  final VoidCallback? onEdit;

  final VoidCallback? onConvertToImage;

  const _FileTile({
    required this.block,
    required this.isReadOnly,
    required this.onTap,
    required this.onDelete,
    required this.onShare,
    this.isPdf = false,
    this.onEdit,
    this.onConvertToImage,
  });

  @override
  State<_FileTile> createState() => _FileTileState();
}

class _FileTileState extends State<_FileTile> {
  final _menuController = lg.GlassMenuController();

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final isDark = theme.brightness == Brightness.dark;
    final rawName = widget.block.displayName.trim();
    final name = (rawName.isEmpty || _isAutogeneratedName(rawName))
        ? 'note_editor_attachment_fallback_name'.tr
        : rawName;
    final ext = rawName.contains('.')
        ? rawName.split('.').last.toUpperCase()
        : '';

    return Semantics(
      button: true,
      label: 'note_editor_attached_file_semantic_label'.trParams({
        'name': name,
      }),
      child: lg.GlassMenu(
        controller: _menuController,
        menuWidth: 250,
        autoAdjustToScreen: true,
        menuPadding: const EdgeInsets.all(12),
        morphFromZero: true,
        triggerBuilder: (context, _) => GestureDetector(
          behavior: HitTestBehavior.opaque,
          onTap: widget.onTap,
          onLongPress: widget.isReadOnly ? null : _menuController.open,
          child: Container(
            padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(14),
              border: Border.all(
                color: isDark
                    ? Colors.white.withValues(alpha: 0.12)
                    : Colors.black.withValues(alpha: 0.08),
                width: 1,
              ),
            ),
            child: Row(
              children: [
                Container(
                  width: 40,
                  height: 40,
                  alignment: Alignment.center,
                  decoration: BoxDecoration(
                    color: theme.colorScheme.surfaceContainerHighest,
                    borderRadius: BorderRadius.circular(10),
                  ),
                  child: Icon(
                    widget.isPdf
                        ? CupertinoIcons.doc_richtext
                        : CupertinoIcons.doc,
                    size: 20,
                    color: theme.colorScheme.onSurfaceVariant,
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        name,
                        maxLines: 1,
                        overflow: TextOverflow.ellipsis,
                        style: theme.textTheme.bodyMedium?.copyWith(
                          fontWeight: FontWeight.w500,
                        ),
                      ),
                      if (ext.isNotEmpty)
                        Text(
                          ext,
                          style: theme.textTheme.bodySmall?.copyWith(
                            color: theme.colorScheme.onSurfaceVariant,
                          ),
                        ),
                    ],
                  ),
                ),
                if (!widget.isReadOnly) ...[
                  if (widget.onEdit != null) ...[
                    GestureDetector(
                      behavior: HitTestBehavior.opaque,
                      onTap: widget.onEdit,
                      child: Icon(
                        CupertinoIcons.pencil,
                        size: 18,
                        color: theme.colorScheme.onSurfaceVariant.withValues(
                          alpha: 0.6,
                        ),
                      ),
                    ),
                    const SizedBox(width: 12),
                  ],
                  GestureDetector(
                    behavior: HitTestBehavior.opaque,
                    onTap: widget.onShare,
                    child: Icon(
                      CupertinoIcons.square_arrow_up,
                      size: 18,
                      color: theme.colorScheme.onSurfaceVariant.withValues(
                        alpha: 0.6,
                      ),
                    ),
                  ),
                  const SizedBox(width: 12),
                  GestureDetector(
                    behavior: HitTestBehavior.opaque,
                    onTap: widget.onDelete,
                    child: Icon(
                      CupertinoIcons.trash,
                      size: 18,
                      color: theme.colorScheme.onSurfaceVariant.withValues(
                        alpha: 0.6,
                      ),
                    ),
                  ),
                ],
              ],
            ),
          ),
        ),
        items: [
          if (widget.isPdf) ...[
            if (widget.onConvertToImage != null)
              lg.GlassMenuItem(
                title: 'note_editor_convert_to_image'.tr,
                icon: const Icon(
                  CupertinoIcons.photo,
                  color: IosSemanticColors.pink,
                ),
                onTap: widget.onConvertToImage!,
              ),
            if (widget.onEdit != null)
              lg.GlassMenuItem(
                title: 'note_editor_edit_original_image'.tr,
                icon: const Icon(
                  CupertinoIcons.pencil,
                  color: IosSemanticColors.blue,
                ),
                onTap: widget.onEdit!,
              ),
            const lg.GlassMenuDivider(),
          ],
          lg.GlassMenuItem(
            title: 'note_editor_open_share'.tr,
            icon: const Icon(
              CupertinoIcons.share,
              color: IosSemanticColors.blue,
            ),
            onTap: widget.onShare,
          ),
          if (!widget.isReadOnly) ...[
            const lg.GlassMenuDivider(),
            lg.GlassMenuItem(
              title: 'note_editor_delete'.tr,
              icon: const Icon(
                CupertinoIcons.trash,
                color: IosSemanticColors.red,
              ),
              isDestructive: true,
              onTap: widget.onDelete,
            ),
          ],
        ],
      ),
    );
  }
}

class _AudioTile extends StatefulWidget {
  final AttachmentBlock block;
  final bool isReadOnly;
  final NoteDetailController controller;
  final VoidCallback onDelete;

  const _AudioTile({
    super.key,
    required this.block,
    required this.isReadOnly,
    required this.controller,
    required this.onDelete,
  });

  @override
  State<_AudioTile> createState() => _AudioTileState();
}

class _AudioTileState extends State<_AudioTile> {
  final _player = AudioPlayer();
  StreamSubscription<Duration>? _durationSub;
  StreamSubscription<Duration>? _positionSub;
  StreamSubscription<void>? _completeSub;

  Duration _duration = Duration.zero;
  Duration _position = Duration.zero;
  bool _isPlaying = false;

  bool _isLoading = false;
  String? _resolvedLocalPath;

  @override
  void initState() {
    super.initState();
    _durationSub = _player.onDurationChanged.listen((d) {
      if (mounted) setState(() => _duration = d);
    });
    _positionSub = _player.onPositionChanged.listen((p) {
      if (mounted) setState(() => _position = p);
    });
    _completeSub = _player.onPlayerComplete.listen((_) {
      if (mounted) {
        setState(() {
          _isPlaying = false;
          _position = Duration.zero;
        });
      }
    });

    final localPath = normalizeLocalPath(widget.block.localPath);
    if (localPath != null && File(localPath).existsSync()) {
      _resolvedLocalPath = localPath;
      unawaited(_player.setSourceDeviceFile(localPath));
    }
  }

  @override
  void dispose() {
    _durationSub?.cancel();
    _positionSub?.cancel();
    _completeSub?.cancel();
    _player.dispose();
    super.dispose();
  }

  Future<void> _togglePlay() async {
    if (_isPlaying) {
      await _player.pause();
      if (mounted) setState(() => _isPlaying = false);
      return;
    }

    var path = _resolvedLocalPath;
    if (path == null) {
      final networkUrl = normalizeAttachmentUrl(widget.block.url);
      if (networkUrl == null) {
        AppSnackbar.info(
          'note_editor_not_available_title'.tr,
          'note_editor_recording_not_on_device'.tr,
        );
        return;
      }

      setState(() => _isLoading = true);
      final name = widget.block.displayName;
      final ext = name.contains('.') ? '.${name.split('.').last}' : '.m4a';
      path = await widget.controller.cacheAttachmentForPlayback(
        networkUrl,
        extension: ext,
      );
      if (mounted) setState(() => _isLoading = false);
      if (path == null) return;
      _resolvedLocalPath = path;
      await _player.setSourceDeviceFile(path);
    }

    try {
      await _player.resume();
      if (mounted) setState(() => _isPlaying = true);
    } catch (e) {
      debugPrint('[AUDIO PLAY ERROR] $e');
      AppSnackbar.error(
        'note_editor_error_title'.tr,
        'note_editor_could_not_play_recording'.tr,
      );
    }
  }

  String _format(Duration d) {
    final minutes = d.inMinutes.remainder(60).toString().padLeft(2, '0');
    final seconds = d.inSeconds.remainder(60).toString().padLeft(2, '0');
    return '$minutes:$seconds';
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final isDark = theme.brightness == Brightness.dark;
    final rawName = widget.block.displayName.trim();
    final name = (rawName.isEmpty || _isAutogeneratedName(rawName))
        ? 'note_editor_recording_fallback_name'.tr
        : rawName;
    final hasDuration = _duration > Duration.zero;

    return Semantics(
      button: true,
      label: 'note_editor_audio_recording_semantic_label'.trParams({
        'name': name,
      }),
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(14),
          border: Border.all(
            color: isDark
                ? Colors.white.withValues(alpha: 0.12)
                : Colors.black.withValues(alpha: 0.08),
            width: 1,
          ),
        ),
        child: Row(
          children: [
            GestureDetector(
              behavior: HitTestBehavior.opaque,
              onTap: _isLoading ? null : _togglePlay,
              child: Container(
                width: 40,
                height: 40,
                alignment: Alignment.center,
                decoration: const BoxDecoration(
                  color: AppTheme.folderPink,
                  shape: BoxShape.circle,
                ),
                child: _isLoading
                    ? const SizedBox(
                        width: 16,
                        height: 16,
                        child: CircularProgressIndicator(
                          strokeWidth: 2,
                          color: Colors.white,
                        ),
                      )
                    : Icon(
                        _isPlaying
                            ? CupertinoIcons.pause_fill
                            : CupertinoIcons.play_fill,
                        size: 18,
                        color: Colors.white,
                      ),
              ),
            ),
            const SizedBox(width: 12),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                mainAxisSize: MainAxisSize.min,
                children: [
                  Text(
                    name,
                    maxLines: 1,
                    overflow: TextOverflow.ellipsis,
                    style: theme.textTheme.bodyMedium?.copyWith(
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                  if (hasDuration)
                    SliderTheme(
                      data: SliderTheme.of(context).copyWith(
                        trackHeight: 2,
                        thumbShape: const RoundSliderThumbShape(
                          enabledThumbRadius: 5,
                        ),
                        overlayShape: const RoundSliderOverlayShape(
                          overlayRadius: 10,
                        ),
                      ),
                      child: Slider(
                        value: _position.inMilliseconds
                            .clamp(0, _duration.inMilliseconds)
                            .toDouble(),
                        max: _duration.inMilliseconds.toDouble(),
                        onChanged: (value) {
                          setState(
                            () => _position = Duration(
                              milliseconds: value.round(),
                            ),
                          );
                        },
                        onChangeEnd: (value) =>
                            _player.seek(Duration(milliseconds: value.round())),
                      ),
                    ),
                  Text(
                    hasDuration
                        ? '${_format(_position)} / ${_format(_duration)}'
                        : 'note_editor_tap_to_play'.tr,
                    style: theme.textTheme.bodySmall?.copyWith(
                      color: theme.colorScheme.onSurfaceVariant,
                    ),
                  ),
                ],
              ),
            ),
            if (!widget.isReadOnly) ...[
              const SizedBox(width: 8),
              GestureDetector(
                behavior: HitTestBehavior.opaque,
                onTap: widget.onDelete,
                child: Icon(
                  CupertinoIcons.trash,
                  size: 18,
                  color: theme.colorScheme.onSurfaceVariant.withValues(
                    alpha: 0.6,
                  ),
                ),
              ),
            ],
          ],
        ),
      ),
    );
  }
}
