/// English strings — every screen in the app. This is also the fallback
/// locale (see `AppTranslations`).
const Map<String, String> enUS = {
  // Splash
  'app_tagline': 'High Fidelity Note Taking',

  // Onboarding
  'onboarding_continue_guest': 'Continue without account',
  'onboarding_create_account': 'Create Account',
  'onboarding_page1_title': 'Capture Ideas',
  'onboarding_page1_desc':
      'Quickly write down your thoughts whenever they strike.',
  'onboarding_page2_title': 'Organize Folders',
  'onboarding_page2_desc':
      'Keep your notes tidy with custom categories and colors.',
  'onboarding_page3_title': 'Sync Anywhere',
  'onboarding_page3_desc':
      'Your notes are always with you, across all your devices.',

  // Shared auth fields
  'phone_number_hint': 'Phone Number',
  'password_hint': 'Password',
  'confirm_password_hint': 'Confirm Password',
  'full_name_hint': 'Full Name',

  // Login
  'login_title': 'Login',
  'login_welcome_back': 'Welcome Back',
  'login_subtitle': 'Login to your account',
  'remember_me': 'Remember Me',
  'forgot_password': 'Forgot Password?',
  'login_button': 'LOGIN',
  'login_no_account': "Don't have an account?",
  'register_link': 'Register',
  'welcome_title': 'Welcome',
  'login_success_message': 'Login successful!',
  'login_failed_title': 'Login Failed',

  // Register
  'register_title': 'Register',
  'register_create_account': 'Create Account',
  'register_subtitle': 'Sign up to get started',
  'register_button': 'REGISTER',
  'register_have_account': 'Already have an account?',
  'login_link': 'Login',
  'success_title': 'Success',
  'register_success_message': 'Account created successfully! Please log in.',
  'register_failed_title': 'Registration Failed',

  // Forgot password sheet
  'forgot_password_title': 'Forgot Password',
  'forgot_password_desc':
      'Enter the phone number linked to your account. We will send instructions to help you reset your password.',
  'phone_number_label': 'Phone number',
  'send_reset_request': 'Send Request',
  'reset_request_sent_title': 'Request Sent',
  'reset_request_sent_message':
      'If an account exists for @phone, you will receive recovery instructions shortly.',

  // Validators
  'validator_phone_required': 'Please enter your phone number.',
  'validator_phone_invalid': 'Please enter a valid phone number (8-15 digits).',
  'validator_password_required': 'Please enter a password.',
  'validator_password_too_short':
      'Password must be at least 6 characters long.',

  // Language picker
  'language_title': 'Languages',

  // Settings
  'settings_title': 'Settings',
  'section_preferences': 'PREFERENCES',
  'section_preferences_footer':
      'Choose how the app looks and how notes behave.',
  'section_support': 'SUPPORT',
  'section_support_footer':
      'Get help or reach out if something isn\'t working.',
  'dark_mode': 'Dark Mode',
  'appearance_title': 'Appearance',
  'note_preferences_title': 'Note Preferences',
  'device_title': 'Device',
  'notifications_title': 'Notifications',
  'privacy_security_title': 'Privacy & Security',
  'device_current': 'Current Device',
  'device_this_device': 'THIS DEVICE',
  'device_storage': 'Note Storage',
  'device_storage_cloud_desc': 'Pii Cloud account storage is active',
  'device_storage_local_desc': 'Notes are stored on this phone',
  'device_account_status': 'Sync Status',
  'device_account_synced': 'Signed in and ready to sync',
  'device_account_local': 'Local-only mode',
  'device_platform_ios': 'Apple mobile device',
  'device_platform_android': 'Android device',
  'device_platform_macos': 'Mac',
  'device_platform_windows': 'Windows device',
  'device_platform_other': 'This device',
  'notifications_confirmations': 'Action Confirmations',
  'notifications_confirmations_desc': 'Show a confirmation after saved actions',
  'notifications_important': 'Important Alerts',
  'notifications_important_desc': 'Errors and security alerts always stay on',
  'privacy_hide_previews': 'Hide Note Previews',
  'privacy_hide_previews_desc': 'Hide note text and images outside the editor',
  'privacy_secure_session': 'Secure Session Storage',
  'privacy_secure_session_desc': 'Sign-in data is protected on this device',
  'privacy_preview_hidden': 'Preview hidden',
  'settings_status_on': 'ON',
  'settings_status_off': 'OFF',
  'share_title': 'Share',
  'share_message':
      'Organize your ideas and notes with Pii Note.\nhttps://piisiit.com',
  'permissions_title': 'Permissions',
  'permissions_subtitle':
      'Review and control the device access used by Pii Note.',
  'permissions_camera': 'Camera',
  'permissions_camera_desc': 'Scan documents and capture images for notes.',
  'permissions_photos': 'Photos',
  'permissions_photos_desc': 'Attach images and save note media.',
  'permissions_microphone': 'Microphone',
  'permissions_microphone_desc': 'Record audio directly inside a note.',
  'permissions_status_allowed': 'Allowed',
  'permissions_status_limited': 'Limited',
  'permissions_status_allow': 'Allow',
  'permissions_status_settings': 'Settings',
  'permissions_status_restricted': 'Restricted',
  'permissions_enabled_title': 'Permission Enabled',
  'permissions_enabled_message': '@permission access is ready to use.',
  'permissions_blocked_title': 'Permission Blocked',
  'permissions_blocked_message':
      'This permission can only be changed in the system App Settings.',
  'permissions_summary_loading': 'Checking device access…',
  'permissions_summary_all': 'All permissions are ready',
  'permissions_summary_count': '@allowed of @total permissions allowed',
  'permissions_tap_hint':
      'Tap Allow to request access. Tap an enabled permission to manage it in Settings.',
  'open_app_settings': 'Open App Settings',
  'pii_business_title': 'Pii Business',
  'privacy_policy_title': 'Privacy Policy',
  'privacy_policy_updated': 'Last updated: August 26, 2026',
  'privacy_policy_intro':
      'Your privacy matters. This summary explains how Pii Note handles information when you use the app.',
  'privacy_policy_data_title': 'Information we use',
  'privacy_policy_data_body':
      'Pii Note uses account details, profile information, notes, folders, and attachments needed to provide the features you choose. Guest notes remain on this device.',
  'privacy_policy_use_title': 'How information is used',
  'privacy_policy_use_body':
      'Information is used to operate your account, save and organize notes, sync signed-in content, and improve reliability. We do not access device features unless you start an action that needs them.',
  'privacy_policy_permissions_title': 'Device permissions',
  'privacy_policy_permissions_body':
      'Camera, photo, and microphone access support scanning, attachments, and audio recording. You can review or revoke access at any time in system settings.',
  'privacy_policy_choices_title': 'Your choices',
  'privacy_policy_choices_body':
      'You can edit profile information, manage permissions, use guest mode, sign out, or request account deletion from Settings.',
  'contact_us_title': 'Contact Us',
  'contact_us_subtitle': 'Choose how you would like to reach the Pii team.',
  'contact_phone': 'Phone',
  'contact_email': 'Gmail',
  'tap_to_call': 'Tap to call',
  'tap_to_email': 'Tap to email',
  'action_unavailable_title': 'Action Unavailable',
  'action_unavailable_message':
      'This action is not available on your current device.',
  'help_center_title': 'Help Center',
  'log_out': 'Log Out',
  'log_in_create_account': 'Log In or Create Account',
  'delete_account_title': 'Delete Account',
  'version_label': 'Version',

  // Profile rename
  'edit_name_title': 'Edit Name',
  'edit_name_hint': 'Enter your name',
  'edit_name_subtitle':
      'This is how your name will appear on your profile and across the app.',
  'name_required_message': 'Please enter your name.',
  'cancel_action': 'Cancel',
  'clear_action': 'Clear',
  'saved_title': 'Saved',
  'name_updated_message': 'Name updated',
  'name_update_failed_title': 'Could not update name',
  'profile_image_updated_message': 'Profile image updated',
  'profile_image_update_failed_title': 'Could not update profile image',
  'profile_image_save_failed_message': 'The selected image could not be saved.',
  'guest_label': 'Guest',
  'default_user_name': 'User Name',
  'not_signed_in': 'Not signed in',

  // Profile View
  'profile_title': 'Profile Details',
  'full_name_label': 'Name',
  'phone_label': 'Phone',
  'guest_status': 'Guest Mode',
  'verified_status_line': 'Verified Account',
  'joined_label': 'Joined',
  'tier_label': 'Account Tier',
  'not_available': 'Not available',
  'save_action': 'Save',
  'done_action': 'Done',
  'profile_updated_message': 'Profile updated',

  // Profile — local-only fields (no backend support yet, see
  // ProfileExtrasStorage)
  'username_label': 'User',
  'account_label': 'Account',
  'email_label': 'Email',
  'job_bio_label': 'Job & Career',
  'color_label': 'Color',
  'edit_username_title': 'Edit User',
  'edit_username_hint': 'Enter a username',
  'edit_account_title': 'Edit Account',
  'edit_account_hint': 'Enter an account name',
  'edit_email_title': 'Edit Email',
  'edit_email_hint': 'Enter your email',
  'edit_job_bio_title': 'Edit Job & Career',
  'edit_job_bio_subtitle': 'Keep your role and career summary up to date.',
  'job_label': 'Job',
  'bio_label': 'Career',
  'edit_job_hint': 'Job title',
  'edit_bio_hint': 'A short career summary',
  'edit_color_title': 'Choose a Color',
  'not_set': 'Not set',

  // Profile — encrypted ID information
  'id_information_title': 'ID Information',
  'id_number_label': 'ID Number',
  'id_name_label': 'Name',
  'date_of_birth_label': 'Date of Birth',
  'edit_id_information_title': 'Edit ID Information',
  'edit_id_information_subtitle':
      'Your identity details are encrypted and stored only for this account on this device.',
  'id_number_hint': 'Enter your ID number',
  'id_name_hint': 'Enter the name shown on your ID',
  'date_of_birth_hint': 'Select your date of birth',
  'id_number_required': 'Please enter your ID number.',
  'id_name_required': 'Please enter the name shown on your ID.',
  'date_of_birth_required': 'Please select your date of birth.',
  'id_information_saved': 'ID information updated',
  'id_information_save_failed_title': 'Could not save ID information',
  'id_information_save_failed_message': 'Please try again.',

  // Settings drawer
  'settings_drawer_view_profile': 'Profile Details',
  'profile_phone_read_only':
      'This phone number belongs to your signed-in account and cannot be changed in the app yet.',

  // Account (delete-account flow)
  'account_title': 'Account',
  'account_delete_account_desc':
      'Permanently deletes your account and all your notes, folders, and attachments. This cannot be undone.',
  'account_delete_confirm_title':
      'Permanently delete your account? All your notes, folders, and attachments will be erased and cannot be recovered.',
  'account_delete_button': 'Delete',
  'account_confirm_password_title': 'Confirm Your Password',
  'account_confirm_password_subtitle':
      'Enter your password to permanently delete your account.',
  'account_deleted_title': 'Account Deleted',
  'account_deleted_message':
      'Your account and its data have been permanently deleted.',
  'account_delete_failed_title': 'Could not delete account',

  // Appearance
  'appearance_system_default': 'System Default',
  'appearance_light_mode': 'Light Mode',

  // Help Center
  'help_center_faq_q1': 'How do I create a note without an account?',
  'help_center_faq_a1':
      'From the welcome screen, tap "Continue without account." Notes you create this way are saved only on this device.',
  'help_center_faq_q2': 'How do I organize notes into folders?',
  'help_center_faq_a2':
      'Tap the "+" on the Pii Cloud or On My Phone section header on the Folders screen to create a folder there, then move notes into it from the note\'s options menu.',
  'help_center_faq_q3': 'How do I hide note previews?',
  'help_center_faq_a3':
      'Go to Settings > Privacy & Security and turn on Hide Note Previews.',
  'help_center_faq_q4': 'Where did a deleted note go?',
  'help_center_faq_a4':
      'Deleted notes and folders move to Recently Deleted, where they can be restored.',

  // Note Preferences
  'note_preferences_default_view': 'Default View',
  'note_preferences_sort_by': 'Sort Notes By',
  'note_preferences_folders_section': 'Folders',
  'note_preferences_list': 'List',
  'note_preferences_grid': 'Grid',
  'note_preferences_date_edited': 'Date Edited',
  'note_preferences_name': 'Name',
  'note_preferences_group_by_date': 'Group by Date',
  'note_preferences_group_by_date_desc': 'Off sorts folders manually, by name',

  // Profile
  'profile_tier_free': 'Free',
  'profile_basic_info': 'Basic Information',
  'profile_change_photo': 'Change Photo',
  'profile_account_settings': 'Account Settings',
  'profile_log_in': 'Log In',

  // Folders
  'folder_title': 'Folders',
  'folder_edit': 'Edit',
  'folder_section_icloud': 'Pii Cloud',
  'folder_section_shared': 'Shared',
  'folder_section_on_my_phone': 'On My Phone',
  'folder_section_sources': 'Sources',
  'folder_tile_subtitle': 'Folder  •  @count notes',
  'folder_move': 'Move Folder',
  'folder_rename': 'Rename Folder',
  'folder_add': 'Add Folder',
  'folder_group_by_date': 'Group By Date',
  'folder_status_on': 'On',
  'folder_status_off': 'Off',
  'folder_delete': 'Delete Folder',
  'folder_convert_smart': 'Convert to Smart Folder',
  'folder_search_semantic': 'Search notes and folders',
  'folder_search_label': 'Search',
  'folder_create_note_semantic': 'Create note',
  'folder_edit_title': 'Edit Folder',
  'folder_new_title': 'New Folder',
  'folder_cancel': 'Cancel',
  'folder_save': 'Save folder',
  'folder_name_label': 'Name',
  'folder_location_label': 'Location',
  'folder_color_label': 'Color',
  'folder_icon_label': 'Icon',
  'folder_emoji_label': 'Emoji',
  'folder_on_my_iphone': 'On My Phone',
  'folder_save_first_title': 'Save first',
  'folder_save_first_message':
      'Save this folder, then make it a Smart Folder from Edit Folder.',
  'folder_make_smart_title': 'Make Into Smart Folder',
  'folder_make_smart_subtitle': 'Organize using tags and other filters',
  'folder_color_semantic': 'Folder color @hex',
  'folder_notes_count_one': 'Folder  •  @count note',
  'folder_notes_count_other': 'Folder  •  @count notes',
  'folder_subfolder_of': 'Subfolder of @parent',
  'folder_no_notes_yet': 'Folder  •  No notes yet',
  'folder_create_folder_in': 'Create folder in @section',
  'folder_recently_deleted': 'Recently Deleted',
  'folder_archive': 'Archive',
  'folder_all_notes': 'All on My Phone',
  'folder_icon_folder': 'Folder',
  'folder_icon_work': 'Work',
  'folder_icon_school': 'School',
  'folder_icon_favorite': 'Favorite',
  'folder_icon_star': 'Star',
  'folder_icon_note': 'Note',
  'folder_icon_home': 'Home',
  'folder_icon_travel': 'Travel',
  'folder_icon_idea': 'Idea',
  'folder_icon_money': 'Money',
  'folder_icon_calendar': 'Calendar',
  'folder_icon_flag': 'Flag',
  'folder_icon_bolt': 'Bolt',
  'folder_icon_game': 'Game',
  'folder_icon_music': 'Music',
  'folder_icon_photo': 'Photo',
  'folder_icon_shopping': 'Shopping',
  'folder_icon_gift': 'Gift',
  'folder_icon_code': 'Code',
  'folder_icon_people': 'People',

  // Note list & navigation
  'note_list_all_notes': 'All Notes',
  'note_list_add_folder': 'Add Folder',
  'note_list_more_options': 'More options',
  'note_list_empty_title': 'No Notes',
  'note_list_pinned': 'Pinned',
  'note_list_notes': 'Notes',
  'note_list_retry': 'Retry',
  'note_list_loading_image': 'Loading Image...',
  'note_list_view_as_gallery': 'View as Gallery',
  'note_list_view_as_list': 'View as List',
  'note_list_select_notes': 'Select Notes',
  'note_list_sort_by': 'Sort By',
  'note_list_sort_name': 'Name',
  'note_list_sort_date_edited': 'Date Edited',
  'note_list_group_by_date': 'Group By Date',
  'note_list_on': 'On',
  'note_list_off': 'Off',
  'note_list_view_attachments': 'View Attachments',
  'note_list_unpin': 'Unpin',
  'note_list_pin': 'Pin',
  'note_list_move': 'Move',
  'note_list_delete': 'Delete',
  'note_list_search_semantic': 'Search notes and folders',
  'note_list_search': 'Search',
  'note_list_create_note': 'Create note',
  'note_list_move_all': 'Move All',
  'note_list_move_count': 'Move (@count)',
  'note_list_delete_all': 'Delete All',
  'note_list_delete_count': 'Delete (@count)',
  'note_list_delete_confirm_title': 'Delete @count Notes?',
  'note_list_delete_confirm_message':
      'These notes will be moved to Recently Deleted.',
  'note_list_folder_note_count': '@count Notes',
  'note_list_new_folder': 'New Folder',
  'note_list_pii_cloud': 'Pii Cloud',
  'note_list_on_my_iphone': 'On My Phone',
  'note_list_select_a_folder': 'Select a Folder',
  'note_list_back': 'Back',
  'note_list_suggested': 'Suggested',
  'note_list_no_results': 'No results found',
  'note_list_folders': 'Folders',
  'note_list_pinned_notes': 'Pinned Notes',
  'note_list_new_note': 'New Note',
  'note_list_archive_title': 'Archive',
  'note_list_edit': 'Edit',
  'note_list_archived_count_one': '@count Note',
  'note_list_archived_count_other': '@count Notes',
  'note_list_archive_description':
      'Archived notes are kept separate from your main notes list. You can restore them at any time.',
  'note_list_no_archived_notes': 'No Archived Notes',
  'note_list_unarchive': 'Unarchive',
  'note_list_info_title': 'Info',
  'note_list_unarchive_coming_soon': 'Unarchive functionality coming soon',

  // Note editor (create + edit)
  'note_editor_title_hint': 'Title',
  'note_editor_start_writing_placeholder': 'Start writing...',
  'note_editor_readonly_banner_message':
      'This note is in Recently Deleted. Restore it to make changes.',
  'note_editor_readonly_tip_title': 'Tip',
  'note_editor_readonly_tip_message':
      'Use Recently Deleted to restore this note.',
  'note_editor_ok': 'OK',
  'note_editor_search_hint': 'Find in note...',
  'note_editor_drawing_options_title': 'Drawing Options',
  'note_editor_delete_drawing': 'Delete Drawing',
  'note_editor_attachment_semantic_label': 'Note attachment',
  'note_editor_attachment_named_semantic_label': 'Attachment: @name',
  'note_editor_image_tap_hint': '. Tap to edit, long press for options.',
  'note_editor_error_title': 'Error',
  'note_editor_image_source_unavailable': 'Image source not available',
  'note_editor_could_not_open_image_editor': 'Could not open image editor',
  'note_editor_not_available_title': 'Not available',
  'note_editor_image_not_on_device': "This image isn't on the device.",
  'note_editor_could_not_share_image': 'Could not share that image',
  'note_editor_file_not_on_device': "This file isn't on the device.",
  'note_editor_could_not_open_file': 'Could not open that file',
  'note_editor_edit_image': 'Edit Image',
  'note_editor_convert_to_pdf': 'Convert to PDF',
  'note_editor_copy': 'Copy',
  'note_editor_paste': 'Paste',
  'note_editor_cut': 'Cut',
  'note_editor_image_copied': 'Image copied',
  'note_editor_could_not_copy_image': 'Could not copy that image',
  'note_editor_attachment_copied': 'Attachment copied',
  'note_editor_attachment_pasted': 'Attachment pasted',
  'note_editor_content_pasted': 'Content pasted',
  'note_editor_attachment_cut': 'Attachment cut',
  'note_editor_nothing_to_paste': 'Nothing to paste',
  'note_editor_could_not_copy_attachment': 'Could not copy that attachment',
  'note_editor_could_not_paste_attachment': 'Could not paste that attachment',
  'note_editor_could_not_cut_attachment': 'Could not cut that attachment',
  'note_editor_view_as': 'View As',
  'note_editor_view_as_small': 'Small',
  'note_editor_view_as_large': 'Large',
  'note_editor_share': 'Share',
  'note_editor_delete': 'Delete',
  'note_editor_attachment_fallback_name': 'Attachment',
  'note_editor_attached_file_semantic_label': 'Attached file: @name',
  'note_editor_convert_to_image': 'Convert to Image',
  'note_editor_edit_original_image': 'Edit Original Image',
  'note_editor_edit_pdf': 'Edit PDF',
  'note_editor_open_share': 'Open / Share',
  'note_editor_recording_not_on_device': "This recording isn't on the device.",
  'note_editor_could_not_play_recording': 'Could not play that recording',
  'note_editor_could_not_share_recording': 'Could not share that recording',
  'note_editor_recording_fallback_name': 'Recording',
  'note_editor_hold_to_record': 'Hold to record',
  'note_editor_slide_to_cancel': 'Slide left to cancel',
  'note_editor_voice_note_saved': 'Voice note saved',
  'note_editor_audio_recording_semantic_label': 'Audio recording: @name',
  'note_editor_tap_to_play': 'Tap to play',
  'note_editor_video_fallback_name': 'Video',
  'note_editor_video_semantic_label': 'Video attachment: @name',
  'note_editor_play_video': 'Play Video',
  'note_editor_video_not_available': 'This video is not available.',
  'note_editor_video_not_on_device': "This video isn't on the device.",
  'note_editor_could_not_share_video': 'Could not share that video',
  'note_editor_scan_text': 'Scan Text',
  'note_editor_scan_docs': 'Scan Documents',
  'note_editor_scanned_document_default_title': 'Scanned Document',
  'note_editor_scanned_text_default_title': 'Scanned Text',
  'note_editor_scan_text_photo': 'Text from Photo',
  'note_editor_scan_docs_photo': 'Document from Photo',
  'note_editor_pdf_page': 'Page',
  'note_editor_pdf_of': 'of',
  'note_editor_open_pdf': 'Open PDF',
  'note_editor_share_print_pdf': 'Share / Print',
  'note_editor_pdf_preview_failed': 'Could not load PDF preview',
  'note_editor_pdf_not_available': 'This PDF is not available.',
  'note_editor_take_photo_video': 'Take Photo or Video',
  'note_editor_choose_photo_video': 'Choose Photo or Video',
  'note_editor_add_image': 'Add Image',
  'note_editor_record_audio': 'Record Audio',
  'note_editor_attach_file': 'Attach File',
  'note_editor_add_item': 'Add Item',
  'note_editor_mark_item_incomplete': 'Mark checklist item incomplete',
  'note_editor_mark_item_complete': 'Mark checklist item complete',
  'note_editor_default_folder_name': 'Notes',
  'note_editor_change_folder_label': 'Change folder',
  'note_editor_folder_updated_title': 'Folder Updated',
  'note_editor_folder_updated_message': 'This note will be saved in @folder.',
  'note_editor_move_success_title': 'Note Moved',
  'note_editor_move_success_message': 'Moved to @folder.',
  'note_editor_move_failed_title': 'Could not move note',
  'note_editor_load_folders_failed_title': 'Could not load folders',
  'note_editor_no_destination_title': 'No Destination',
  'note_editor_no_destination_message': 'Create another folder first.',
  'note_editor_saving_indicator': '  ·  Saving…',
  'note_editor_undo_label': 'Undo',
  'note_editor_checklist_label': 'Checklist',
  'note_editor_attachment_label': 'Attachment',
  'note_editor_format_label': 'Format',
  'note_editor_create_note_label': 'Create note',
  'note_editor_drawing_label': 'Drawing',
  'note_editor_table_label': 'Table',
  'note_editor_bold_label': 'Bold',
  'note_editor_italic_label': 'Italic',
  'note_editor_underline_label': 'Underline',
  'note_editor_bullet_list_label': 'Bullet list',
  'note_editor_numbered_list_label': 'Numbered list',
  'note_editor_link_label': 'Link',
  'note_editor_strikethrough_label': 'Strikethrough',
  'note_editor_highlight_label': 'Highlight',
  'note_editor_align_left_label': 'Align left',
  'note_editor_indent_label': 'Indent',
  'note_editor_link_title': 'Add Link',
  'note_editor_link_text_hint': 'Text to display',
  'note_editor_link_url_hint': 'https://example.com',
  'note_editor_link_add': 'Add Link',
  'note_editor_link_focus_message': 'Place the cursor in your note first.',
  'note_editor_invalid_link_title': 'Invalid Link',
  'note_editor_invalid_link_message': 'Enter a valid website address.',
  'note_editor_format_title': 'Format',
  'note_editor_style_title': 'Title',
  'note_editor_style_heading': 'Heading',
  'note_editor_style_subheading': 'Subheading',
  'note_editor_style_body': 'Body',
  'note_editor_unpin': 'Unpin',
  'note_editor_pin': 'Pin',
  'note_editor_unarchive': 'Unarchive',
  'note_editor_archive': 'Archive',
  'note_editor_unlock': 'Unlock',
  'note_editor_lock': 'Lock',
  'note_editor_move': 'Move',
  'note_editor_find_in_note': 'Find in Note',
  'note_editor_export_pdf': 'Export as PDF',
  'note_editor_mic_unavailable_title': 'Microphone unavailable',
  'note_editor_mic_unavailable_message':
      'Enable microphone access in Settings to record audio.',
  'note_editor_could_not_start_recording': 'Could not start recording',
  'note_editor_cancel': 'Cancel',
  'note_editor_done': 'Done',
  'note_editor_recording_starting': 'Starting…',
  'note_editor_recording_status': 'Recording',
  'note_editor_recording_paused': 'Paused',
  'note_editor_recording_saving': 'Saving recording…',
  'note_editor_recording_updating': 'Updating…',
  'note_editor_pause_recording': 'Pause recording',
  'note_editor_resume_recording': 'Resume recording',
  'note_editor_save_recording': 'Save recording',
  'note_editor_review_recording': 'Stop',
  'note_editor_record_again': 'Record Again',
  'note_editor_play_preview': 'Play',
  'note_editor_pause_preview': 'Pause',
  'note_editor_playing_preview': 'Playing Preview',
  'note_editor_ready_to_save': 'Ready to Save',
  'note_editor_could_not_prepare_review':
      'Could not prepare this recording for review.',
  'note_editor_live_waveform': 'Live audio waveform',
  'note_editor_recording_hint': 'Speak clearly near your microphone',
  'note_editor_tap_resume_hint': 'Tap Resume to continue recording',
  'note_editor_could_not_change_recording':
      'Could not pause or resume the recording.',
  'note_editor_could_not_save_recording': 'Could not save the recording.',
  'note_editor_recording_too_short_title': 'Recording too short',
  'note_editor_recording_too_short_message':
      'Record for at least half a second before saving.',
  'note_editor_row_label': 'Row',
  'note_editor_column_label': 'Column',

  // Recently Deleted (Trash)
  'trash_title': 'Recently Deleted',
  'trash_edit': 'Edit',
  'trash_item_count_one': '@count Item',
  'trash_item_count_other': '@count Items',
  'trash_retention_notice':
      'Notes are available here for 30 days. After that time, notes will be permanently deleted. This may take up to 40 days.',
  'trash_empty_state': 'No Deleted Items',
  'trash_folders_section': 'Folders',
  'trash_notes_section': 'Notes',
  'trash_folder_subtitle': 'Folder  •  @count notes',
  'trash_restore_note_message':
      'This note is in Recently Deleted. You must restore it before viewing or editing.',
  'trash_restore_folder_message':
      'This folder is in Recently Deleted. You must restore it before viewing or editing.',
  'trash_restore': 'Restore',
  'trash_delete': 'Delete',
  'trash_recover': 'Recover',
  'trash_move': 'Move',
  'trash_delete_permanently': 'Delete Permanently',
};
