/// English strings — every screen in the app. This is also the fallback
/// locale (see `AppTranslations`).
const Map<String, String> enUS = {
  // Splash
  'app_tagline': 'High Fidelity Note Taking',

  // Onboarding
  'onboarding_continue_guest': 'Continue without account',
  'onboarding_create_account': 'Create Account',
  'onboarding_page1_title': 'Capture Ideas',
  'onboarding_page1_desc':
      'Quickly write down your thoughts whenever they strike.',
  'onboarding_page2_title': 'Organize Folders',
  'onboarding_page2_desc':
      'Keep your notes tidy with custom categories and colors.',
  'onboarding_page3_title': 'Sync Anywhere',
  'onboarding_page3_desc':
      'Your notes are always with you, across all your devices.',

  // Shared auth fields
  'phone_number_hint': 'Phone Number',
  'password_hint': 'Password',
  'confirm_password_hint': 'Confirm Password',
  'full_name_hint': 'Full Name',

  // Login
  'login_title': 'Login',
  'login_welcome_back': 'Welcome Back',
  'login_subtitle': 'Login to your account',
  'remember_me': 'Remember Me',
  'forgot_password': 'Forgot Password?',
  'login_button': 'LOGIN',
  'login_no_account': "Don't have an account?",
  'register_link': 'Register',
  'welcome_title': 'Welcome',
  'login_success_message': 'Login successful!',
  'login_failed_title': 'Login Failed',

  // Register
  'register_title': 'Register',
  'register_create_account': 'Create Account',
  'register_subtitle': 'Sign up to get started',
  'register_button': 'REGISTER',
  'register_have_account': 'Already have an account?',
  'login_link': 'Login',
  'success_title': 'Success',
  'register_success_message': 'Account created successfully! Please log in.',
  'register_failed_title': 'Registration Failed',

  // Forgot password sheet
  'reset_password_title': 'Reset Password',
  'reset_password_desc':
      'Enter your phone number to receive a password reset link.',
  'send_reset_link': 'SEND RESET LINK',
  'invalid_phone_title': 'Invalid phone',
  'reset_request_sent_title': 'Request Sent',
  'reset_request_sent_message':
      'If an account exists for @phone, you will receive a reset link shortly.',

  // Validators
  'validator_phone_required': 'Please enter your phone number.',
  'validator_phone_invalid': 'Please enter a valid phone number (8-15 digits).',
  'validator_password_required': 'Please enter a password.',
  'validator_password_too_short':
      'Password must be at least 6 characters long.',

  // Language picker
  'language_title': 'Languages',

  // Settings
  'settings_title': 'Settings',
  'section_preferences': 'PREFERENCES',
  'section_preferences_footer':
      'Choose how the app looks and how notes behave.',
  'section_support': 'SUPPORT',
  'section_support_footer':
      'Get help or reach out if something isn\'t working.',
  'dark_mode': 'Dark Mode',
  'appearance_title': 'Appearance',
  'note_preferences_title': 'Note Preferences',
  'help_center_title': 'Help Center',
  'log_out': 'Log Out',
  'log_in_create_account': 'Log In or Create Account',
  'delete_account_title': 'Delete Account',
  'version_label': 'Version',

  // Profile rename
  'edit_name_title': 'Edit Name',
  'edit_name_hint': 'Enter your name',
  'saved_title': 'Saved',
  'name_updated_message': 'Name updated',
  'name_update_failed_title': 'Could not update name',
  'profile_image_updated_message': 'Profile image updated',
  'profile_image_update_failed_title': 'Could not update profile image',
  'guest_label': 'Guest',
  'default_user_name': 'User Name',
  'not_signed_in': 'Not signed in',

  // Profile View
  'profile_title': 'Profile Details',
  'full_name_label': 'Name',
  'phone_label': 'Phone',
  'guest_status': 'Guest Mode',
  'verified_status_line': 'Verified Account',
  'joined_label': 'Joined',
  'tier_label': 'Account Tier',
  'not_available': 'Not available',
  'save_action': 'Save',
  'profile_updated_message': 'Profile updated',

  // Profile — local-only fields (no backend support yet, see
  // ProfileExtrasStorage)
  'username_label': 'User',
  'account_label': 'Account',
  'email_label': 'Email',
  'job_bio_label': 'Job & Bio',
  'color_label': 'Color',
  'edit_username_title': 'Edit User',
  'edit_username_hint': 'Enter a username',
  'edit_account_title': 'Edit Account',
  'edit_account_hint': 'Enter an account name',
  'edit_email_title': 'Edit Email',
  'edit_email_hint': 'Enter your email',
  'edit_job_bio_title': 'Edit Job & Bio',
  'edit_job_hint': 'Job title',
  'edit_bio_hint': 'A short bio',
  'edit_color_title': 'Choose a Color',
  'not_set': 'Not set',

  // Settings drawer
  'settings_drawer_view_profile': 'Profile Details',

  // Account (delete-account flow)
  'account_title': 'Account',
  'account_delete_account_desc':
      'Permanently deletes your account and all your notes, folders, and attachments. This cannot be undone.',
  'account_delete_confirm_title':
      'Permanently delete your account? All your notes, folders, and attachments will be erased and cannot be recovered.',
  'account_delete_button': 'Delete',
  'account_confirm_password_title': 'Confirm Your Password',
  'account_confirm_password_subtitle':
      'Enter your password to permanently delete your account.',
  'account_deleted_title': 'Account Deleted',
  'account_deleted_message':
      'Your account and its data have been permanently deleted.',
  'account_delete_failed_title': 'Could not delete account',

  // Appearance
  'appearance_system_default': 'System Default',
  'appearance_light_mode': 'Light Mode',

  // Help Center
  'help_center_faq_q1': 'How do I create a note without an account?',
  'help_center_faq_a1':
      'From the welcome screen, tap "Continue without account." Notes you create this way are saved only on this device.',
  'help_center_faq_q2': 'How do I organize notes into folders?',
  'help_center_faq_a2':
      'Tap the "+" on the Pii Cloud or On My Phone section header on the Folders screen to create a folder there, then move notes into it from the note\'s options menu.',
  'help_center_faq_q3': "How do I change the app's appearance?",
  'help_center_faq_a3':
      'Go to Settings > Appearance and choose System Default, Light, or Dark.',
  'help_center_faq_q4': 'Where did a deleted note go?',
  'help_center_faq_a4':
      'Deleted notes and folders move to Recently Deleted, where they can be restored.',

  // Note Preferences
  'note_preferences_default_view': 'Default View',
  'note_preferences_sort_by': 'Sort Notes By',
  'note_preferences_folders_section': 'Folders',
  'note_preferences_list': 'List',
  'note_preferences_grid': 'Grid',
  'note_preferences_date_edited': 'Date Edited',
  'note_preferences_name': 'Name',
  'note_preferences_group_by_date': 'Group by Date',
  'note_preferences_group_by_date_desc': 'Off sorts folders manually, by name',

  // Profile
  'profile_tier_free': 'Free',
  'profile_basic_info': 'Basic Information',
  'profile_change_photo': 'Change Photo',
  'profile_account_settings': 'Account Settings',
  'profile_log_in': 'Log In',

  // Folders
  'folder_title': 'Folders',
  'folder_edit': 'Edit',
  'folder_section_icloud': 'Pii Cloud',
  'folder_section_shared': 'Shared',
  'folder_section_on_my_phone': 'On My Phone',
  'folder_section_sources': 'Sources',
  'folder_tile_subtitle': 'Folder  •  @count notes',
  'folder_move': 'Move Folder',
  'folder_rename': 'Rename Folder',
  'folder_add': 'Add Folder',
  'folder_group_by_date': 'Group By Date',
  'folder_status_on': 'On',
  'folder_status_off': 'Off',
  'folder_delete': 'Delete Folder',
  'folder_convert_smart': 'Convert to Smart Folder',
  'folder_search_semantic': 'Search notes and folders',
  'folder_search_label': 'Search',
  'folder_create_note_semantic': 'Create note',
  'folder_edit_title': 'Edit Folder',
  'folder_new_title': 'New Folder',
  'folder_cancel': 'Cancel',
  'folder_save': 'Save folder',
  'folder_name_label': 'Name',
  'folder_location_label': 'Location',
  'folder_color_label': 'Color',
  'folder_icon_label': 'Icon',
  'folder_emoji_label': 'Emoji',
  'folder_on_my_iphone': 'On My iPhone',
  'folder_save_first_title': 'Save first',
  'folder_save_first_message':
      'Save this folder, then make it a Smart Folder from Edit Folder.',
  'folder_make_smart_title': 'Make Into Smart Folder',
  'folder_make_smart_subtitle': 'Organize using tags and other filters',
  'folder_color_semantic': 'Folder color @hex',
  'folder_notes_count_one': 'Folder  •  @count note',
  'folder_notes_count_other': 'Folder  •  @count notes',
  'folder_subfolder_of': 'Subfolder of @parent',
  'folder_no_notes_yet': 'Folder  •  No notes yet',
  'folder_create_folder_in': 'Create folder in @section',
  'folder_recently_deleted': 'Recently Deleted',
  'folder_archive': 'Archive',
  'folder_all_notes': 'All on My iPhone',
  'folder_icon_folder': 'Folder',
  'folder_icon_work': 'Work',
  'folder_icon_school': 'School',
  'folder_icon_favorite': 'Favorite',
  'folder_icon_star': 'Star',
  'folder_icon_note': 'Note',
  'folder_icon_home': 'Home',
  'folder_icon_travel': 'Travel',
  'folder_icon_idea': 'Idea',
  'folder_icon_money': 'Money',
  'folder_icon_calendar': 'Calendar',
  'folder_icon_flag': 'Flag',
  'folder_icon_bolt': 'Bolt',
  'folder_icon_game': 'Game',
  'folder_icon_music': 'Music',
  'folder_icon_photo': 'Photo',
  'folder_icon_shopping': 'Shopping',
  'folder_icon_gift': 'Gift',
  'folder_icon_code': 'Code',
  'folder_icon_people': 'People',

  // Note list & navigation
  'note_list_all_notes': 'All Notes',
  'note_list_add_folder': 'Add Folder',
  'note_list_more_options': 'More options',
  'note_list_empty_title': 'No Notes',
  'note_list_pinned': 'Pinned',
  'note_list_notes': 'Notes',
  'note_list_retry': 'Retry',
  'note_list_loading_image': 'Loading Image...',
  'note_list_view_as_gallery': 'View as Gallery',
  'note_list_view_as_list': 'View as List',
  'note_list_select_notes': 'Select Notes',
  'note_list_sort_by': 'Sort By',
  'note_list_sort_name': 'Name',
  'note_list_sort_date_edited': 'Date Edited',
  'note_list_group_by_date': 'Group By Date',
  'note_list_on': 'On',
  'note_list_off': 'Off',
  'note_list_view_attachments': 'View Attachments',
  'note_list_unpin': 'Unpin',
  'note_list_pin': 'Pin',
  'note_list_move': 'Move',
  'note_list_delete': 'Delete',
  'note_list_search_semantic': 'Search notes and folders',
  'note_list_search': 'Search',
  'note_list_create_note': 'Create note',
  'note_list_move_all': 'Move All',
  'note_list_move_count': 'Move (@count)',
  'note_list_delete_all': 'Delete All',
  'note_list_delete_count': 'Delete (@count)',
  'note_list_delete_confirm_title': 'Delete @count Notes?',
  'note_list_delete_confirm_message':
      'These notes will be moved to Recently Deleted.',
  'note_list_folder_note_count': '@count Notes',
  'note_list_new_folder': 'New Folder',
  'note_list_pii_cloud': 'Pii Cloud',
  'note_list_on_my_iphone': 'On My iPhone',
  'note_list_select_a_folder': 'Select a Folder',
  'note_list_back': 'Back',
  'note_list_suggested': 'Suggested',
  'note_list_no_results': 'No results found',
  'note_list_folders': 'Folders',
  'note_list_pinned_notes': 'Pinned Notes',
  'note_list_new_note': 'New Note',
  'note_list_archive_title': 'Archive',
  'note_list_edit': 'Edit',
  'note_list_archived_count_one': '@count Note',
  'note_list_archived_count_other': '@count Notes',
  'note_list_archive_description':
      'Archived notes are kept separate from your main notes list. You can restore them at any time.',
  'note_list_no_archived_notes': 'No Archived Notes',
  'note_list_unarchive': 'Unarchive',
  'note_list_info_title': 'Info',
  'note_list_unarchive_coming_soon': 'Unarchive functionality coming soon',

  // Note editor (create + edit)
  'note_editor_title_hint': 'Title',
  'note_editor_start_writing_placeholder': 'Start writing...',
  'note_editor_readonly_banner_message':
      'This note is in Recently Deleted. Restore it to make changes.',
  'note_editor_readonly_tip_title': 'Tip',
  'note_editor_readonly_tip_message':
      'Use Recently Deleted to restore this note.',
  'note_editor_ok': 'OK',
  'note_editor_search_hint': 'Find in note...',
  'note_editor_drawing_options_title': 'Drawing Options',
  'note_editor_delete_drawing': 'Delete Drawing',
  'note_editor_attachment_semantic_label': 'Note attachment',
  'note_editor_attachment_named_semantic_label': 'Attachment: @name',
  'note_editor_image_tap_hint': '. Tap to edit, long press for options.',
  'note_editor_error_title': 'Error',
  'note_editor_image_source_unavailable': 'Image source not available',
  'note_editor_could_not_open_image_editor': 'Could not open image editor',
  'note_editor_not_available_title': 'Not available',
  'note_editor_image_not_on_device': "This image isn't on the device.",
  'note_editor_could_not_share_image': 'Could not share that image',
  'note_editor_file_not_on_device': "This file isn't on the device.",
  'note_editor_could_not_open_file': 'Could not open that file',
  'note_editor_edit_image': 'Edit Image',
  'note_editor_convert_to_pdf': 'Convert to PDF',
  'note_editor_share': 'Share',
  'note_editor_delete': 'Delete',
  'note_editor_attachment_fallback_name': 'Attachment',
  'note_editor_attached_file_semantic_label': 'Attached file: @name',
  'note_editor_convert_to_image': 'Convert to Image',
  'note_editor_edit_original_image': 'Edit Original Image',
  'note_editor_open_share': 'Open / Share',
  'note_editor_recording_not_on_device': "This recording isn't on the device.",
  'note_editor_could_not_play_recording': 'Could not play that recording',
  'note_editor_recording_fallback_name': 'Recording',
  'note_editor_audio_recording_semantic_label': 'Audio recording: @name',
  'note_editor_tap_to_play': 'Tap to play',
  'note_editor_scan_text': 'Scan Text',
  'note_editor_scan_docs': 'Scan Documents',
  'note_editor_take_photo_video': 'Take Photo or Video',
  'note_editor_choose_photo_video': 'Choose Photo or Video',
  'note_editor_record_audio': 'Record Audio',
  'note_editor_attach_file': 'Attach File',
  'note_editor_add_item': 'Add Item',
  'note_editor_mark_item_incomplete': 'Mark checklist item incomplete',
  'note_editor_mark_item_complete': 'Mark checklist item complete',
  'note_editor_default_folder_name': 'Notes',
  'note_editor_saving_indicator': '  ·  Saving…',
  'note_editor_checklist_label': 'Checklist',
  'note_editor_attachment_label': 'Attachment',
  'note_editor_format_label': 'Format',
  'note_editor_create_note_label': 'Create note',
  'note_editor_drawing_label': 'Drawing',
  'note_editor_table_label': 'Table',
  'note_editor_bold_label': 'Bold',
  'note_editor_italic_label': 'Italic',
  'note_editor_underline_label': 'Underline',
  'note_editor_bullet_list_label': 'Bullet list',
  'note_editor_numbered_list_label': 'Numbered list',
  'note_editor_link_label': 'Link',
  'note_editor_strikethrough_label': 'Strikethrough',
  'note_editor_highlight_label': 'Highlight',
  'note_editor_align_left_label': 'Align left',
  'note_editor_indent_label': 'Indent',
  'note_editor_link_title': 'Add Link',
  'note_editor_link_text_hint': 'Text to display',
  'note_editor_link_url_hint': 'https://example.com',
  'note_editor_link_add': 'Add Link',
  'note_editor_link_focus_message': 'Place the cursor in your note first.',
  'note_editor_invalid_link_title': 'Invalid Link',
  'note_editor_invalid_link_message': 'Enter a valid website address.',
  'note_editor_format_title': 'Format',
  'note_editor_style_title': 'Title',
  'note_editor_style_heading': 'Heading',
  'note_editor_style_subheading': 'Subheading',
  'note_editor_style_body': 'Body',
  'note_editor_unpin': 'Unpin',
  'note_editor_pin': 'Pin',
  'note_editor_unarchive': 'Unarchive',
  'note_editor_archive': 'Archive',
  'note_editor_unlock': 'Unlock',
  'note_editor_lock': 'Lock',
  'note_editor_move': 'Move',
  'note_editor_find_in_note': 'Find in Note',
  'note_editor_export_pdf': 'Export as PDF',
  'note_editor_mic_unavailable_title': 'Microphone unavailable',
  'note_editor_mic_unavailable_message':
      'Enable microphone access in Settings to record audio.',
  'note_editor_could_not_start_recording': 'Could not start recording',
  'note_editor_cancel': 'Cancel',
  'note_editor_recording_starting': 'Starting…',
  'note_editor_recording_status': 'Recording',
  'note_editor_row_label': 'Row',
  'note_editor_column_label': 'Column',

  // Recently Deleted (Trash)
  'trash_title': 'Recently Deleted',
  'trash_edit': 'Edit',
  'trash_item_count_one': '@count Item',
  'trash_item_count_other': '@count Items',
  'trash_retention_notice':
      'Notes are available here for 30 days. After that time, notes will be permanently deleted. This may take up to 40 days.',
  'trash_empty_state': 'No Deleted Items',
  'trash_folders_section': 'Folders',
  'trash_notes_section': 'Notes',
  'trash_folder_subtitle': 'Folder  •  @count notes',
  'trash_restore_note_message':
      'This note is in Recently Deleted. You must restore it before viewing or editing.',
  'trash_restore_folder_message':
      'This folder is in Recently Deleted. You must restore it before viewing or editing.',
  'trash_restore': 'Restore',
  'trash_delete': 'Delete',
  'trash_recover': 'Recover',
  'trash_move': 'Move',
  'trash_delete_permanently': 'Delete Permanently',
};
