/// Khmer strings — mirrors the key set in `en_us.dart`. Any key missing here
/// falls back to English via `AppTranslations.fallbackLocale`.
const Map<String, String> kmKH = {
  // Splash
  'app_tagline': 'ការកត់ត្រាគុណភាពខ្ពស់',

  // Onboarding
  'onboarding_continue_guest': 'បន្តដោយមិនប្រើគណនី',
  'onboarding_create_account': 'បង្កើតគណនី',
  'onboarding_page1_title': 'កត់ត្រាគំនិត',
  'onboarding_page1_desc': 'កត់ត្រាគំនិតរបស់អ្នកយ៉ាងរហ័ស នៅពេលណាដែលវាកើតឡើង។',
  'onboarding_page2_title': 'រៀបចំថតឯកសារ',
  'onboarding_page2_desc':
      'រក្សាកំណត់ត្រារបស់អ្នកឱ្យមានសណ្តាប់ធ្នាប់ ជាមួយប្រភេទ និងពណ៌ផ្ទាល់ខ្លួន។',
  'onboarding_page3_title': 'ធ្វើសមកាលកម្មគ្រប់ទីកន្លែង',
  'onboarding_page3_desc':
      'កំណត់ត្រារបស់អ្នកនៅជាមួយអ្នកជានិច្ច នៅលើគ្រប់ឧបករណ៍។',

  // Shared auth fields
  'phone_number_hint': 'លេខទូរស័ព្ទ',
  'password_hint': 'ពាក្យសម្ងាត់',
  'confirm_password_hint': 'បញ្ជាក់ពាក្យសម្ងាត់',
  'full_name_hint': 'ឈ្មោះពេញ',

  // Login
  'login_title': 'ចូល',
  'login_welcome_back': 'សូមស្វាគមន៍មកវិញ',
  'login_subtitle': 'ចូលទៅកាន់គណនីរបស់អ្នក',
  'remember_me': 'ចងចាំខ្ញុំ',
  'forgot_password': 'ភ្លេចពាក្យសម្ងាត់?',
  'login_button': 'ចូល',
  'login_no_account': 'មិនទាន់មានគណនីមែនទេ?',
  'register_link': 'ចុះឈ្មោះ',
  'welcome_title': 'សូមស្វាគមន៍',
  'login_success_message': 'ចូលដោយជោគជ័យ!',
  'login_failed_title': 'ការចូលបានបរាជ័យ',

  // Register
  'register_title': 'ចុះឈ្មោះ',
  'register_create_account': 'បង្កើតគណនី',
  'register_subtitle': 'ចុះឈ្មោះដើម្បីចាប់ផ្តើម',
  'register_button': 'ចុះឈ្មោះ',
  'register_have_account': 'មានគណនីរួចហើយមែនទេ?',
  'login_link': 'ចូល',
  'success_title': 'ជោគជ័យ',
  'register_success_message': 'បង្កើតគណនីដោយជោគជ័យ! សូមចូល។',
  'register_failed_title': 'ការចុះឈ្មោះបានបរាជ័យ',

  // Forgot password sheet
  'reset_password_title': 'កំណត់ពាក្យសម្ងាត់ឡើងវិញ',
  'reset_password_desc':
      'បញ្ចូលលេខទូរស័ព្ទរបស់អ្នក ដើម្បីទទួលបានតំណកំណត់ពាក្យសម្ងាត់ឡើងវិញ។',
  'send_reset_link': 'ផ្ញើតំណកំណត់ឡើងវិញ',
  'invalid_phone_title': 'លេខទូរស័ព្ទមិនត្រឹមត្រូវ',
  'reset_request_sent_title': 'បានផ្ញើសំណើ',
  'reset_request_sent_message':
      'ប្រសិនបើមានគណនីសម្រាប់ @phone អ្នកនឹងទទួលបានតំណកំណត់ឡើងវិញឆាប់ៗនេះ។',

  // Validators
  'validator_phone_required': 'សូមបញ្ចូលលេខទូរស័ព្ទរបស់អ្នក។',
  'validator_phone_invalid': 'សូមបញ្ចូលលេខទូរស័ព្ទត្រឹមត្រូវ (8-15 ខ្ទង់)។',
  'validator_password_required': 'សូមបញ្ចូលពាក្យសម្ងាត់។',
  'validator_password_too_short': 'ពាក្យសម្ងាត់ត្រូវមានយ៉ាងតិច 6 តួអក្សរ។',

  // Language picker
  'language_title': 'ភាសា',

  // Settings
  'settings_title': 'ការកំណត់',
  'section_preferences': 'ចំណូលចិត្ត',
  'section_preferences_footer':
      'ជ្រើសរើសរបៀបដែលកម្មវិធីបង្ហាញ និងរបៀបដែលកំណត់ត្រាដំណើរការ។',
  'section_support': 'ជំនួយ',
  'section_support_footer': 'ស្វែងរកជំនួយ ឬទាក់ទងមកកាន់យើងប្រសិនបើមានបញ្ហា។',
  'dark_mode': 'របៀបងងឹត',
  'appearance_title': 'រូបរាង',
  'note_preferences_title': 'ចំណូលចិត្តកំណត់ត្រា',
  'help_center_title': 'មជ្ឈមណ្ឌលជំនួយ',
  'log_out': 'ចាកចេញ',
  'log_in_create_account': 'ចូល ឬបង្កើតគណនី',
  'delete_account_title': 'លុបគណនី',
  'version_label': 'កំណែ',

  // Profile rename
  'edit_name_title': 'កែឈ្មោះ',
  'edit_name_hint': 'បញ្ចូលឈ្មោះរបស់អ្នក',
  'edit_name_subtitle': 'ឈ្មោះនេះនឹងបង្ហាញនៅលើប្រវត្តិរូប និងក្នុងកម្មវិធី។',
  'name_required_message': 'សូមបញ្ចូលឈ្មោះរបស់អ្នក។',
  'cancel_action': 'បោះបង់',
  'clear_action': 'សម្អាត',
  'saved_title': 'បានរក្សាទុក',
  'name_updated_message': 'ឈ្មោះត្រូវបានធ្វើបច្ចុប្បន្នភាព',
  'name_update_failed_title': 'មិនអាចធ្វើបច្ចុប្បន្នភាពឈ្មោះបានទេ',
  'profile_image_updated_message':
      'រូបភាពប្រវត្តិរូបត្រូវបានធ្វើបច្ចុប្បន្នភាព',
  'profile_image_update_failed_title':
      'មិនអាចធ្វើបច្ចុប្បន្នភាពរូបភាពប្រវត្តិរូបបានទេ',
  'guest_label': 'ភ្ញៀវ',
  'default_user_name': 'ឈ្មោះអ្នកប្រើប្រាស់',
  'not_signed_in': 'មិនទាន់ចូលគណនី',

  // Profile View
  'profile_title': 'ព័ត៌មានប្រវត្តិរូប',
  'full_name_label': 'ឈ្មោះ',
  'phone_label': 'ទូរស័ព្ទ',
  'guest_status': 'របៀបភ្ញៀវ',
  'verified_status_line': 'គណនីបានផ្ទៀងផ្ទាត់',
  'joined_label': 'បានចូលរួម',
  'tier_label': 'កម្រិតគណនី',
  'not_available': 'មិនមាន',
  'save_action': 'រក្សាទុក',
  'done_action': 'រួចរាល់',
  'profile_updated_message': 'ព័ត៌មានប្រវត្តិរូបត្រូវបានធ្វើបច្ចុប្បន្នភាព',

  // Profile — local-only fields (no backend support yet, see
  // ProfileExtrasStorage)
  'username_label': 'អ្នកប្រើ',
  'account_label': 'គណនី',
  'email_label': 'អ៊ីមែល',
  'job_bio_label': 'មុខរបរ និងជីវប្រវត្តិសង្ខេប',
  'color_label': 'ពណ៌',
  'edit_username_title': 'កែអ្នកប្រើ',
  'edit_username_hint': 'បញ្ចូលឈ្មោះអ្នកប្រើ',
  'edit_account_title': 'កែគណនី',
  'edit_account_hint': 'បញ្ចូលឈ្មោះគណនី',
  'edit_email_title': 'កែអ៊ីមែល',
  'edit_email_hint': 'បញ្ចូលអ៊ីមែលរបស់អ្នក',
  'edit_job_bio_title': 'កែមុខរបរ និងជីវប្រវត្តិសង្ខេប',
  'edit_job_hint': 'តួនាទីការងារ',
  'edit_bio_hint': 'ជីវប្រវត្តិសង្ខេប',
  'edit_color_title': 'ជ្រើសរើសពណ៌',
  'not_set': 'មិនទាន់កំណត់',

  // Settings drawer
  'settings_drawer_view_profile': 'ព័ត៌មានប្រវត្តិរូប',

  // Account (delete-account flow)
  'account_title': 'គណនី',
  'account_delete_account_desc':
      'លុបគណនីរបស់អ្នក និងកំណត់ត្រា ថត និងឯកសារភ្ជាប់ទាំងអស់ជាអចិន្ត្រៃយ៍។ សកម្មភាពនេះមិនអាចត្រឡប់វិញបានទេ។',
  'account_delete_confirm_title':
      'លុបគណនីរបស់អ្នកជាអចិន្ត្រៃយ៍ឬ? កំណត់ត្រា ថត និងឯកសារភ្ជាប់ទាំងអស់របស់អ្នកនឹងត្រូវលុប ហើយមិនអាចយកមកវិញបានទេ។',
  'account_delete_button': 'លុប',
  'account_confirm_password_title': 'បញ្ជាក់ពាក្យសម្ងាត់របស់អ្នក',
  'account_confirm_password_subtitle':
      'បញ្ចូលពាក្យសម្ងាត់របស់អ្នក ដើម្បីលុបគណនីជាអចិន្ត្រៃយ៍។',
  'account_deleted_title': 'គណនីត្រូវបានលុប',
  'account_deleted_message':
      'គណនី និងទិន្នន័យរបស់អ្នកត្រូវបានលុបជាអចិន្ត្រៃយ៍។',
  'account_delete_failed_title': 'មិនអាចលុបគណនីបានទេ',

  // Appearance
  'appearance_system_default': 'លំនាំដើមប្រព័ន្ធ',
  'appearance_light_mode': 'របៀបភ្លឺ',

  // Help Center
  'help_center_faq_q1': 'តើខ្ញុំបង្កើតកំណត់ត្រាដោយមិនប្រើគណនីយ៉ាងដូចម្តេច?',
  'help_center_faq_a1':
      'ពីអេក្រង់ស្វាគមន៍ សូមចុច "បន្តដោយមិនប្រើគណនី"។ កំណត់ត្រាដែលបង្កើតតាមរបៀបនេះ រក្សាទុកតែនៅលើឧបករណ៍នេះប៉ុណ្ណោះ។',
  'help_center_faq_q2': 'តើខ្ញុំរៀបចំកំណត់ត្រាទៅក្នុងថតយ៉ាងដូចម្តេច?',
  'help_center_faq_a2':
      'ចុច "+" នៅក្បាលផ្នែក Pii Cloud ឬ On My Phone នៅលើអេក្រង់ថត ដើម្បីបង្កើតថតនៅទីនោះ រួចផ្លាស់ទីកំណត់ត្រាចូលទៅក្នុងវាពីម៉ឺនុយជម្រើសរបស់កំណត់ត្រា។',
  'help_center_faq_q3': 'តើខ្ញុំផ្លាស់ប្តូររូបរាងកម្មវិធីយ៉ាងដូចម្តេច?',
  'help_center_faq_a3':
      'ចូលទៅកាន់ ការកំណត់ > រូបរាង ហើយជ្រើសរើស លំនាំដើមប្រព័ន្ធ ភ្លឺ ឬងងឹត។',
  'help_center_faq_q4': 'តើកំណត់ត្រាដែលបានលុបទៅណា?',
  'help_center_faq_a4':
      'កំណត់ត្រា និងថតដែលបានលុបនឹងផ្លាស់ទៅ "បានលុបថ្មីៗ" ដែលអាចយកមកវិញបាន។',

  // Note Preferences
  'note_preferences_default_view': 'ទិដ្ឋភាពលំនាំដើម',
  'note_preferences_sort_by': 'តម្រៀបកំណត់ត្រាតាម',
  'note_preferences_folders_section': 'ថត',
  'note_preferences_list': 'បញ្ជី',
  'note_preferences_grid': 'ក្រឡាចត្រង្គ',
  'note_preferences_date_edited': 'កាលបរិច្ឆេទកែសម្រួល',
  'note_preferences_name': 'ឈ្មោះ',
  'note_preferences_group_by_date': 'ដាក់ជាក្រុមតាមកាលបរិច្ឆេទ',
  'note_preferences_group_by_date_desc': 'បិទ នឹងតម្រៀបថតដោយដៃ តាមឈ្មោះ',

  // Profile
  'profile_tier_free': 'ឥតគិតថ្លៃ',
  'profile_basic_info': 'ព័ត៌មានមូលដ្ឋាន',
  'profile_change_photo': 'ប្តូររូបភាព',
  'profile_account_settings': 'ការកំណត់គណនី',
  'profile_log_in': 'ចូល',

  // Folders
  'folder_title': 'ថត',
  'folder_edit': 'កែសម្រួល',
  'folder_section_icloud': 'Pii Cloud',
  'folder_section_shared': 'បានចែករំលែក',
  'folder_section_on_my_phone': 'នៅលើទូរស័ព្ទខ្ញុំ',
  'folder_section_sources': 'ប្រភព',
  'folder_tile_subtitle': 'ថត  •  @count កំណត់ត្រា',
  'folder_move': 'ផ្លាស់ទីថត',
  'folder_rename': 'ប្តូរឈ្មោះថត',
  'folder_add': 'បន្ថែមថត',
  'folder_group_by_date': 'ដាក់ជាក្រុមតាមកាលបរិច្ឆេទ',
  'folder_status_on': 'បើក',
  'folder_status_off': 'បិទ',
  'folder_delete': 'លុបថត',
  'folder_convert_smart': 'បំប្លែងទៅជាថតឆ្លាតវៃ',
  'folder_search_semantic': 'ស្វែងរកកំណត់ត្រា និងថត',
  'folder_search_label': 'ស្វែងរក',
  'folder_create_note_semantic': 'បង្កើតកំណត់ត្រា',
  'folder_edit_title': 'កែសម្រួលថត',
  'folder_new_title': 'ថតថ្មី',
  'folder_cancel': 'បោះបង់',
  'folder_save': 'រក្សាទុកថត',
  'folder_name_label': 'ឈ្មោះ',
  'folder_location_label': 'ទីតាំង',
  'folder_color_label': 'ពណ៌',
  'folder_icon_label': 'រូបតំណាង',
  'folder_emoji_label': 'សញ្ញាអារម្មណ៍',
  'folder_on_my_iphone': 'នៅលើទូរស័ព្ទខ្ញុំ',
  'folder_save_first_title': 'រក្សាទុកមុនសិន',
  'folder_save_first_message':
      'រក្សាទុកថតនេះជាមុនសិន រួចធ្វើវាទៅជាថតឆ្លាតវៃពី កែសម្រួលថត។',
  'folder_make_smart_title': 'ធ្វើទៅជាថតឆ្លាតវៃ',
  'folder_make_smart_subtitle': 'រៀបចំដោយប្រើស្លាក និងតម្រងផ្សេងទៀត',
  'folder_color_semantic': 'ពណ៌ថត @hex',
  'folder_notes_count_one': 'ថត  •  @count កំណត់ត្រា',
  'folder_notes_count_other': 'ថត  •  @count កំណត់ត្រា',
  'folder_subfolder_of': 'ថតរងនៃ @parent',
  'folder_no_notes_yet': 'ថត  •  មិនទាន់មានកំណត់ត្រា',
  'folder_create_folder_in': 'បង្កើតថតនៅក្នុង @section',
  'folder_recently_deleted': 'បានលុបថ្មីៗ',
  'folder_archive': 'ប័ណ្ណសារ',
  'folder_all_notes': 'ទាំងអស់នៅលើ iPhone ខ្ញុំ',
  'folder_icon_folder': 'ថត',
  'folder_icon_work': 'ការងារ',
  'folder_icon_school': 'សាលារៀន',
  'folder_icon_favorite': 'សំណព្វ',
  'folder_icon_star': 'ផ្កាយ',
  'folder_icon_note': 'កំណត់ត្រា',
  'folder_icon_home': 'ផ្ទះ',
  'folder_icon_travel': 'ធ្វើដំណើរ',
  'folder_icon_idea': 'គំនិត',
  'folder_icon_money': 'លុយ',
  'folder_icon_calendar': 'ប្រតិទិន',
  'folder_icon_flag': 'ទង់',
  'folder_icon_bolt': 'បន្ទោរអគ្គិសនី',
  'folder_icon_game': 'ល្បែង',
  'folder_icon_music': 'តន្ត្រី',
  'folder_icon_photo': 'រូបភាព',
  'folder_icon_shopping': 'ការទិញឥវ៉ាន់',
  'folder_icon_gift': 'អំណោយ',
  'folder_icon_code': 'កូដ',
  'folder_icon_people': 'មនុស្ស',

  // Note list & navigation
  'note_list_all_notes': 'កំណត់ត្រាទាំងអស់',
  'note_list_add_folder': 'បន្ថែមថត',
  'note_list_more_options': 'ជម្រើសបន្ថែម',
  'note_list_empty_title': 'មិនមានកំណត់ត្រា',
  'note_list_pinned': 'បានខ្ទាស់',
  'note_list_notes': 'កំណត់ត្រា',
  'note_list_retry': 'ព្យាយាមម្តងទៀត',
  'note_list_loading_image': 'កំពុងផ្ទុករូបភាព...',
  'note_list_view_as_gallery': 'មើលជាវិចិត្រសាល',
  'note_list_view_as_list': 'មើលជាបញ្ជី',
  'note_list_select_notes': 'ជ្រើសរើសកំណត់ត្រា',
  'note_list_sort_by': 'តម្រៀបតាម',
  'note_list_sort_name': 'ឈ្មោះ',
  'note_list_sort_date_edited': 'កាលបរិច្ឆេទកែសម្រួល',
  'note_list_group_by_date': 'ដាក់ជាក្រុមតាមកាលបរិច្ឆេទ',
  'note_list_on': 'បើក',
  'note_list_off': 'បិទ',
  'note_list_view_attachments': 'មើលឯកសារភ្ជាប់',
  'note_list_unpin': 'ដកការខ្ទាស់',
  'note_list_pin': 'ខ្ទាស់',
  'note_list_move': 'ផ្លាស់ទី',
  'note_list_delete': 'លុប',
  'note_list_search_semantic': 'ស្វែងរកកំណត់ត្រា និងថត',
  'note_list_search': 'ស្វែងរក',
  'note_list_create_note': 'បង្កើតកំណត់ត្រា',
  'note_list_move_all': 'ផ្លាស់ទីទាំងអស់',
  'note_list_move_count': 'ផ្លាស់ទី (@count)',
  'note_list_delete_all': 'លុបទាំងអស់',
  'note_list_delete_count': 'លុប (@count)',
  'note_list_delete_confirm_title': 'លុបកំណត់ត្រា @count ឬ?',
  'note_list_delete_confirm_message':
      'កំណត់ត្រាទាំងនេះនឹងផ្លាស់ទៅ "បានលុបថ្មីៗ"។',
  'note_list_folder_note_count': '@count កំណត់ត្រា',
  'note_list_new_folder': 'ថតថ្មី',
  'note_list_pii_cloud': 'Pii Cloud',
  'note_list_on_my_iphone': 'នៅលើទូរស័ព្ទខ្ញុំ',
  'note_list_select_a_folder': 'ជ្រើសរើសថត',
  'note_list_back': 'ត្រឡប់ក្រោយ',
  'note_list_suggested': 'ណែនាំ',
  'note_list_no_results': 'រកមិនឃើញលទ្ធផល',
  'note_list_folders': 'ថត',
  'note_list_pinned_notes': 'កំណត់ត្រាបានខ្ទាស់',
  'note_list_new_note': 'កំណត់ត្រាថ្មី',
  'note_list_archive_title': 'ប័ណ្ណសារ',
  'note_list_edit': 'កែសម្រួល',
  'note_list_archived_count_one': '@count កំណត់ត្រា',
  'note_list_archived_count_other': '@count កំណត់ត្រា',
  'note_list_archive_description':
      'កំណត់ត្រាដែលបានទុកក្នុងប័ណ្ណសារ ត្រូវបានផ្តាច់ដោយឡែកពីបញ្ជីកំណត់ត្រាចម្បងរបស់អ្នក។ អ្នកអាចយកមកវិញបានគ្រប់ពេល។',
  'note_list_no_archived_notes': 'មិនមានកំណត់ត្រាក្នុងប័ណ្ណសារ',
  'note_list_unarchive': 'យកចេញពីប័ណ្ណសារ',
  'note_list_info_title': 'ព័ត៌មាន',
  'note_list_unarchive_coming_soon': 'មុខងារយកចេញពីប័ណ្ណសារនឹងមកដល់ឆាប់ៗនេះ',

  // Note editor (create + edit)
  'note_editor_title_hint': 'ចំណងជើង',
  'note_editor_start_writing_placeholder': 'ចាប់ផ្តើមសរសេរ...',
  'note_editor_readonly_banner_message':
      'កំណត់ត្រានេះស្ថិតនៅក្នុង "បានលុបថ្មីៗ"។ សូមយកមកវិញដើម្បីធ្វើការផ្លាស់ប្តូរ។',
  'note_editor_readonly_tip_title': 'គន្លឹះ',
  'note_editor_readonly_tip_message':
      'ប្រើ "បានលុបថ្មីៗ" ដើម្បីយកកំណត់ត្រានេះមកវិញ។',
  'note_editor_ok': 'យល់ព្រម',
  'note_editor_search_hint': 'ស្វែងរកក្នុងកំណត់ត្រា...',
  'note_editor_drawing_options_title': 'ជម្រើសគំនូរ',
  'note_editor_delete_drawing': 'លុបគំនូរ',
  'note_editor_attachment_semantic_label': 'ឯកសារភ្ជាប់កំណត់ត្រា',
  'note_editor_attachment_named_semantic_label': 'ឯកសារភ្ជាប់៖ @name',
  'note_editor_image_tap_hint': '។ ចុចដើម្បីកែសម្រួល ចុចឱ្យយូរសម្រាប់ជម្រើស។',
  'note_editor_error_title': 'កំហុស',
  'note_editor_image_source_unavailable': 'មិនមានប្រភពរូបភាព',
  'note_editor_could_not_open_image_editor':
      'មិនអាចបើកកម្មវិធីកែសម្រួលរូបភាពបានទេ',
  'note_editor_not_available_title': 'មិនអាចប្រើបាន',
  'note_editor_image_not_on_device': 'រូបភាពនេះមិននៅលើឧបករណ៍នេះទេ។',
  'note_editor_could_not_share_image': 'មិនអាចចែករំលែករូបភាពនោះបានទេ',
  'note_editor_file_not_on_device': 'ឯកសារនេះមិននៅលើឧបករណ៍នេះទេ។',
  'note_editor_could_not_open_file': 'មិនអាចបើកឯកសារនោះបានទេ',
  'note_editor_edit_image': 'កែសម្រួលរូបភាព',
  'note_editor_convert_to_pdf': 'បំប្លែងទៅជា PDF',
  'note_editor_share': 'ចែករំលែក',
  'note_editor_delete': 'លុប',
  'note_editor_attachment_fallback_name': 'ឯកសារភ្ជាប់',
  'note_editor_attached_file_semantic_label': 'ឯកសារភ្ជាប់៖ @name',
  'note_editor_convert_to_image': 'បំប្លែងទៅជារូបភាព',
  'note_editor_edit_original_image': 'កែសម្រួលរូបភាពដើម',
  'note_editor_open_share': 'បើក / ចែករំលែក',
  'note_editor_recording_not_on_device': 'ការថតសំឡេងនេះមិននៅលើឧបករណ៍នេះទេ។',
  'note_editor_could_not_play_recording': 'មិនអាចចាក់ការថតសំឡេងនោះបានទេ',
  'note_editor_recording_fallback_name': 'ការថតសំឡេង',
  'note_editor_audio_recording_semantic_label': 'ការថតសំឡេង៖ @name',
  'note_editor_tap_to_play': 'ចុចដើម្បីចាក់',
  'note_editor_scan_text': 'ស្កេនអត្ថបទ',
  'note_editor_scan_docs': 'ស្កេនឯកសារ',
  'note_editor_take_photo_video': 'ថតរូបភាព ឬវីដេអូ',
  'note_editor_choose_photo_video': 'ជ្រើសរើសរូបភាព ឬវីដេអូ',
  'note_editor_record_audio': 'ថតសំឡេង',
  'note_editor_attach_file': 'ភ្ជាប់ឯកសារ',
  'note_editor_add_item': 'បន្ថែមធាតុ',
  'note_editor_mark_item_incomplete': 'សម្គាល់ធាតុថាមិនទាន់ធ្វើ',
  'note_editor_mark_item_complete': 'សម្គាល់ធាតុថាបានធ្វើរួច',
  'note_editor_default_folder_name': 'កំណត់ត្រា',
  'note_editor_change_folder_label': 'ប្តូរថត',
  'note_editor_folder_updated_title': 'បានធ្វើបច្ចុប្បន្នភាពថត',
  'note_editor_folder_updated_message':
      'កំណត់ត្រានេះនឹងត្រូវរក្សាទុកក្នុង @folder។',
  'note_editor_move_success_title': 'បានផ្លាស់ទីកំណត់ត្រា',
  'note_editor_move_success_message': 'បានផ្លាស់ទីទៅ @folder។',
  'note_editor_move_failed_title': 'មិនអាចផ្លាស់ទីកំណត់ត្រាបានទេ',
  'note_editor_load_folders_failed_title': 'មិនអាចផ្ទុកថតបានទេ',
  'note_editor_no_destination_title': 'មិនមានថតគោលដៅ',
  'note_editor_no_destination_message': 'សូមបង្កើតថតផ្សេងមួយជាមុនសិន។',
  'note_editor_saving_indicator': '  ·  កំពុងរក្សាទុក…',
  'note_editor_undo_label': 'មិនធ្វើវិញ',
  'note_editor_checklist_label': 'បញ្ជីត្រូវធ្វើ',
  'note_editor_attachment_label': 'ឯកសារភ្ជាប់',
  'note_editor_format_label': 'ទម្រង់',
  'note_editor_create_note_label': 'បង្កើតកំណត់ត្រា',
  'note_editor_drawing_label': 'គំនូរ',
  'note_editor_table_label': 'តារាង',
  'note_editor_bold_label': 'អក្សរដិត',
  'note_editor_italic_label': 'អក្សរទ្រេត',
  'note_editor_underline_label': 'គូសបន្ទាត់ក្រោម',
  'note_editor_bullet_list_label': 'បញ្ជីចំណុច',
  'note_editor_numbered_list_label': 'បញ្ជីលេខ',
  'note_editor_link_label': 'តំណ',
  'note_editor_strikethrough_label': 'គូសកាត់អត្ថបទ',
  'note_editor_highlight_label': 'រំលេច',
  'note_editor_align_left_label': 'តម្រឹមឆ្វេង',
  'note_editor_indent_label': 'បង្កើនការចូលបន្ទាត់',
  'note_editor_link_title': 'បន្ថែមតំណ',
  'note_editor_link_text_hint': 'អត្ថបទបង្ហាញ',
  'note_editor_link_url_hint': 'https://example.com',
  'note_editor_link_add': 'បន្ថែមតំណ',
  'note_editor_link_focus_message': 'ដាក់ទ្រនិចនៅក្នុងកំណត់ត្រាសិន។',
  'note_editor_invalid_link_title': 'តំណមិនត្រឹមត្រូវ',
  'note_editor_invalid_link_message': 'បញ្ចូលអាសយដ្ឋានគេហទំព័រដែលត្រឹមត្រូវ។',
  'note_editor_format_title': 'ទម្រង់',
  'note_editor_style_title': 'ចំណងជើង',
  'note_editor_style_heading': 'ក្បាលអត្ថបទ',
  'note_editor_style_subheading': 'ក្បាលអត្ថបទរង',
  'note_editor_style_body': 'អត្ថបទ',
  'note_editor_unpin': 'ដកការខ្ទាស់',
  'note_editor_pin': 'ខ្ទាស់',
  'note_editor_unarchive': 'យកចេញពីប័ណ្ណសារ',
  'note_editor_archive': 'ដាក់ក្នុងប័ណ្ណសារ',
  'note_editor_unlock': 'ដោះសោ',
  'note_editor_lock': 'ចាក់សោ',
  'note_editor_move': 'ផ្លាស់ទី',
  'note_editor_find_in_note': 'ស្វែងរកក្នុងកំណត់ត្រា',
  'note_editor_export_pdf': 'នាំចេញជា PDF',
  'note_editor_mic_unavailable_title': 'មិនអាចប្រើមីក្រូហ្វូនបានទេ',
  'note_editor_mic_unavailable_message':
      'បើកសិទ្ធិប្រើមីក្រូហ្វូននៅក្នុងការកំណត់ ដើម្បីថតសំឡេង។',
  'note_editor_could_not_start_recording': 'មិនអាចចាប់ផ្តើមថតសំឡេងបានទេ',
  'note_editor_cancel': 'បោះបង់',
  'note_editor_recording_starting': 'កំពុងចាប់ផ្តើម…',
  'note_editor_recording_status': 'កំពុងថត',
  'note_editor_row_label': 'ជួរដេក',
  'note_editor_column_label': 'ជួរឈរ',

  // Recently Deleted (Trash)
  'trash_title': 'បានលុបថ្មីៗ',
  'trash_edit': 'កែសម្រួល',
  'trash_item_count_one': '@count ធាតុ',
  'trash_item_count_other': '@count ធាតុ',
  'trash_retention_notice':
      'កំណត់ត្រានៅទីនេះមានរយៈពេល 30 ថ្ងៃ។ បន្ទាប់ពីនោះ កំណត់ត្រានឹងត្រូវលុបជាអចិន្ត្រៃយ៍។ វាអាចចំណាយពេលរហូតដល់ 40 ថ្ងៃ។',
  'trash_empty_state': 'មិនមានធាតុដែលបានលុប',
  'trash_folders_section': 'ថត',
  'trash_notes_section': 'កំណត់ត្រា',
  'trash_folder_subtitle': 'ថត  •  @count កំណត់ត្រា',
  'trash_restore_note_message':
      'កំណត់ត្រានេះស្ថិតនៅក្នុង "បានលុបថ្មីៗ"។ អ្នកត្រូវយកវាមកវិញសិន មុននឹងមើល ឬកែសម្រួល។',
  'trash_restore_folder_message':
      'ថតនេះស្ថិតនៅក្នុង "បានលុបថ្មីៗ"។ អ្នកត្រូវយកវាមកវិញសិន មុននឹងមើល ឬកែសម្រួល។',
  'trash_restore': 'យកមកវិញ',
  'trash_delete': 'លុប',
  'trash_recover': 'ស្តារឡើងវិញ',
  'trash_move': 'ផ្លាស់ទី',
  'trash_delete_permanently': 'លុបជាអចិន្ត្រៃយ៍',
};
